### ISSUE TITLE
New Issue Template: build

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1021]
Current issue templates don't help when submitting "unable to build" issues.

**Comment by ryanRfox** [comment]
I'm open to how best to improve the issue submission workflow. I'll offer my thoughts on how it is currently implemented, then request others to suggest alternatives.

Currently, the BitShares-Core repo uses two (2) Issue Templates to guide the user through the Issue creation process and aid the Core Team in capturing relevant information up front to assist in evaluating and prioritizing for future development.  

1) `Bug Report` - Create a detailed report about a deficiency in the BitShares Core implementation.
2) `Feature Request` - Suggest an idea for the BitShares Core Team to evaluate and prioritize for development.

The user should evaluate if the issue they are raising is `bug` in the existing implementation, or `feature` to extend the current implementation. We offer these two choices to prompt the user to consider their issue type initially, as distinct information is required within each template thereafter, thus allowing the Core Team to capture more relevant information. The Core Team intends to address `bugs` ahead of `features` or `enhancements`. The implementation _should_ function as designed, and be remedied quickly when it does not. The `Bug Report` guides the user through providing information about the steps leading to the error condition, their expectations for success criteria and various environmental conditions. The `Feature Request` is generalized to a _User Story_ template in the format:
As a `<persona>` I want `<some functionality>` so that `<some benefit is realized>`. Here also are included a number of _Impacts_ which match up to the Labels (prefix 6) such as API, Build, US, etc. These assist both the Core Team and users in identifying and searching for specific impacts to the code of various issues.

Again, I am keen to provide a user experience which is intuitive, streamlined and captures relevant information for the Core Team to act on. Suggestions are welcome below.

**Comment by ryanRfox** [comment]
A potential improvement could be the addition of the `Impacts` section to the `Bug Report` to allow the user to indicate which areas of the software the bug impacts. Please indicate if this will improve the user experience and information gather for use by the Core Team in their evaluation of the Issue.

**Comment by ryanRfox** [comment]
Responding directly to the OP about "unable to build" issues: I feel this should be logged as a `Bug Report` by the user. The implementation is not functioning as designed.

**Comment by abitmore** [comment]
A build-related issue is usually a question. Usually the user (usually a newcomer) doesn't know if it's a bug or a missing feature. But we DO want him to provide useful info in the first place, E.G. steps to reproduce, OS/boost/openssl version, detailed output of `cmake` and `make` commands and etc.

See #1020 for reference.

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/issues/1020

we need to ask for:
    * source code branch/tag: [e.g. 2.0.180425]
    * SSL version: [e.g. OpenSSL 1.0.2g 1 Mar 2016]
    * Boost version: [e.g. 1.62]
    * Host OS: [e.g. Ubuntu 17.10]

A new issue type "building" or something is for me what fit best.

**Comment by oxarbitrage** [comment]
oops, commented at the same time than @abitmore , sorry.
as he says there(https://github.com/bitshares/bitshares-core/issues/1021#issuecomment-394703187) we don't know if it is a bug(an os and versions that should be supported by building) or a feature(building in new enviroment).

**Comment by oxarbitrage** [comment]
another minor thing to consider that i don't like much about our current issue templates is that the checkboxes for user selection are considered by github as tasks. i don't have a solution for this other than actually change the tasklist to something else after the issuer makes the initial selection.

**Comment by ryanRfox** [comment]
Thank you @abit for providing the user case and reference to the Issue. I will draft a new template for building. 

Thank you @oxarbitrage for the comment about the checkboxes. My intention with these in the template is to prompt the user for the Impacts. Once they submit the Issue, we (organization members) can (should) edit the Issue:
* Add Labels:
  * The `6 Series` of Labels should be tagged based on user indicated impacts, personal intuition)
  * Set the `1, 2, 3 Series` Labels (Issue Type, Status, Classification respectively)
  * Set other Labels as needed 
* Edit Description: 
  * Remove Impacts section (they are now Labels)
  * Remove sections the user did not complete (many are optional, irrelevant to specific Issue)
  * Refactor User Story
* Add Issue to `Project Backlog` Project Board (will default to `New`) 

At this point, the Issue should now only contain the `CORE TEAM TASK LIST` which we can then tick off as we progress with development.

**Comment by oxarbitrage** [comment]
fixed with https://github.com/bitshares/bitshares-core/pull/1030
