### ISSUE TITLE
BSIP 29: Potential Problems

### ISSUE THREAD

**Issue by arminnaderi** [bitshares/bitshares-core#1027]
I discussed these issues with @abitmore recently, but we want to see what the rest of the developers here think about this issue. I currently see a couple of potential problems arising if the current implementation of BSIP 29 was to move to the mainnet:

1. Lots of clients will have broken code from the increased operation count;
2. The operation list currently consists of around 56 operations, that's simply a lot operations and complexity for client code to deal with and adding another operation does not help alleviate this problem;
3. Requiring owner permissions for the transfer of an asset is only helpful for MPAs, PMs, and assets that are very restricted in issuer permissions. If a normal asset gets compromised, the last thing people will be concerned about is the asset itself if all their funds have already been stolen and sold;
4. @xeroc also mentioned a potential problem with this BSIP outlined in [the BSIP 29 issue](https://github.com/bitshares/bitshares-core/issues/199#issuecomment-383068258). Basically, if someone accidentally changes the issuer of an asset to `committee-account` then the asset becomes irrecoverable since the the committee account does not have owner keys.

For all the mentioned reasons (1-3), and the possible side effects from implementing this BSIP in the mainnet (4), it doesn't seem to be worth it since it seems like one step forward and a couple steps backward. I am curious to see what everyone thinks of my criticisms of this BSIP. Please let me know if I missed any facts/details and if you agree/disagree. Thanks.

RELATED LINKS:

- [BSIP 29 issue](https://github.com/bitshares/bitshares-core/issues/199)
- [BSIP 29](https://github.com/bitshares/bsips/blob/master/bsip-0029.md)

**Comment by pmconrad** [comment]
It's a bit late for this discussion. BSIP-29 has already been approved by the shareholders and is implemented in the upcoming release. Because of the shareholder approval this is also the wrong place for this discussion. Please bring it up on BitSharesTalk, or create another BSIP. Closing here.

My personal opinion is that your reasons are not valid.
As to reasons 1 and 2, clients can choose to be either be robust and deal with operation ids that they do not understand, or to be careful and die if they see an unknown operation id. It's up to the owner and the specific application to make that choice. We (as the BitShares community) cannot let ourselves be stalled by potential client problems and refrain from ever adding new operations to the core.

Reason 3 is also invalid, as this is a general security measure that applies to *all* assets.

Number 4 is unfortunate, but it can be remedied in a future hardfork.
