### ISSUE TITLE
Remove temp-account balance check

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1040]

**Comment by btsabc** [comment]
Before making a thorough understanding of the impact of blind transfer, it is best not to do so.

**Comment by pmconrad** [comment]
@btsabc please elaborate your concerns. AFAICS blind transfers will not be negatively impacted by this change.

**Comment by christophersanborn** [comment]
Curious for the motivation here.  Off the top of my head I can't think of a detriment to blind transfers, but I don't know for sure that there isn't one.

**Comment by christophersanborn** [comment]
Worst case that I can think of (but not necessarily worst case that exists) is if an un-blind operation (Op 41) leaves some asset amount unclaimed after revealing the blinding factor for an ownerless commitment, (typically created by a preceding Op 40 within the same transaction).  (I’m not even sure why/how the temp-account is involved in that, actually, except that it must be that the “ownerless” balance is virtualized as belonging to the temp-account, or something along those lines. Or maybe it’s because the temp-account is paying the fees?  It’s something though, because when one inspects temp-account on Cryptofresh the TX history is all blind operations.)

This could result in lost funds for the user, but only it the user’s wallet failed to claim the full balance. It would require malformed wallet software to do this, since obviously a well-designed wallet would claim the entire balance for the user. 

However I would expect (but don’t know offhand where to check this) that the validation of Op 41 explicitly checks that the claimed balance matches the un-blinded balance, so that such a malformed transaction would fail for other reasons, not just because the temp account was left with a non-zero balance, so this *shouldn’t* be an issue.  In any case, I don’t think it would violate asset conservation.

This is just an off-the-top-of-my-head assessment however.  I don’t know if there aren’t other concerns to address.

**Comment by abitmore** [comment]
Fixed with #1041. Closing this issue now. Please feel free to reopen it or create a new issue if found something wrong.
