### ISSUE TITLE
Change more 32 bit data fields to 64 bit

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1206]
Here are some, please add new findings.
* account_statistics_object
  * total_ops
  * removed_ops
* account_transaction_history_object
  * sequence

#1088 is related.

**Comment by jmjatlanta** [comment]
Un-assigning myself, and leaving this ticket open so we can keep track of other items that should be switched from 32 to 64 bit.

**Comment by crypto-ape** [comment]
Block timestamp is stored as an unsigned 32-bit value (`block_header::timestamp`).

This won't be an issue in near future but will cause failure by 2038 (if the source is 32-bit signed integer) or at the latest by 2106 (see [year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem)).

We don't need to worry about the operating system providing correct time (which it sure will) but about the BitShares' codebase. It seems the `class time_point_sec` representing the Unix Epoch time in fc library is fed by the `class microseconds` which stores its timestamp with an 64-bit integer. Thus if no bits are lost during the conversions and manipulations we are probably talking about the year 2106. Yet, simple comparisons in `ifs` can cause temporal overflows resulting in bugs occurring sooner.

Actually, all the Unix Epoch time manipulations by means of the `class time_point_sec` may (and will) fail, sooner or later.

Ape proposes the following:
 * Extend the internal field of the `class time_point_sec` to 64-bit unsigned integer and change the code appropriately.
 * Separately, inspect the time source and fix if necessary.
 * In order to save some space, leave the block header timestamp field as 32-bit until some (to be agreed) safe date (e.g. 2034).

**Comment by pmconrad** [comment]
Changing time representation now is a waste of time IMO. Can revisit the issue in 15 years.

**Comment by clockworkgr** [comment]
> Changing time representation now is a waste of time IMO. Can revisit the issue in 15 years.

was gonna say...if this codebase is still around in 2038, we'll all probably be too rich to care :D

**Comment by jmjatlanta** [comment]
The original issue has been fixed in #1347 . It would be best that if any others are found, please create a new issue.
