### ISSUE TITLE
Improve performance of elasticsearch plugin

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1224]
**User Story**

As a `elasticsearch node operator` I want `the replay to be faster`.

Elasticsearch plugin replay can take a lot of time to synchronize the blockchain. Depending on hardware the process can be of 10 hours, 30 hours or even 3 days.

3 ideas to research and implement:

- Try different elasticsearch config options like window time, heap memory, etc. This is outside core task but updates on the subject can be posted here.

Tasks  inside core:
- [ ] From https://github.com/bitshares/bitshares-core/issues/1103 we have: "Refactor elasticsearch plugin logic(performance, don't create and delete objects, mimic the object id numeration)."
- [ ] From https://github.com/bitshares/bitshares-core/pull/1122#issuecomment-408459638 : try to use some moves instead of copying this much.

Others suggestions of course welcome.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Important: decouple ES processing from block processing thread as much as possible

**Comment by ryanRfox** [comment]
I'm not sure how relevant this is: please review the patterns used within [Demux](https://github.com/EOSIO/demux-js) and described in their [introduction](https://medium.com/eosio/introducing-demux-deterministic-databases-off-chain-verified-by-the-eosio-blockchain-bd860c49b017).

**Comment by oxarbitrage** [comment]
Yesterday i started to synchronize the mainnet with the code in the following branch:
https://github.com/bitshares/bitshares-core/pull/1249

The pull above apply some moves instead of copies in an attempt to make the replay process faster.

It also reduce some object passing that was not needed in some functions among some other things. 
I will like @pmconrad  to take a look at those changes when he haves time.

One of the changes was the remove of the parsing of the bulk response, this was added for error checking inside the bulk response from elastic(for example a bad parsed request) however this response come with detailed json of all the operations inside the bulk. This means we were getting a huge string of response, jsonizing it with `fc::json::from_string` just to check the `error` field in the header. 
The main problem of removing this check if that somehow we send a wrong operation mapping we will not get the error but with current plugin and blockchain status this never happened in the lifetime of the mainnet.

In this attempt i tried a few elasticsearch setting changes. 

- In  a 32 G server  i added 20G to `jvm.options` with: 
```
 -Xms20g
 -Xmx20g
```
- with a template, i added a 5 minutes refresh window and no replicas for all the bitshares-* indexes with(not possible to do this anymore from the config file in the last versions of ES):
 ```
curl -XPOST 'http://localhost:9200/_template/template1' -H 'Content-Type: application/json' -d '{ "index_patterns" : ["bitshares-*"], "settings": {"refresh_interval": "300s", "number_of_replicas": 0} }'
```
this settings need to be reversed after sync for real time indexing.

- fired the witness node with 100k bulks with command:
```
programs/witness_node/witness_node --plugins "witness elasticsearch" --elasticsearch-bulk-replay 100000
```

The sync goes fast up to 90% of the blockchain then it start to slow down, some parts of it in the last few months are eternal. This could be explained with the amount of operations in the last months, they had been a lot more than before but it also seems some parts of the blockchain (after last HF?)  are computational more expensive than they were before.  This summed up to the bot activity of “downloadbot” who made more than 108 million of operations all alone in the last 2 months: http://bitshares-explorer.io/#/accounts/downloadsbot2

Still, last attempt was more than 32 hours, close than a month ago, this one was 26 hours total and with almost 1 month more of data with downloadbot in action(now it stopped luckily).

This metrics were taken when the chain was close to sync but not fully, at around 2018-07-10:
```
    coreadmin@CORE-01:~$ curl -X GET --silent 'http://localhost:9200/bitshares-*/_count' | jq
    {
      "count": 283600000,
      "_shards": {
        "total": 170,
        "successful": 170,
        "skipped": 0,
        "failed": 0
      }
    }
    coreadmin@CORE-01:~$ 
```
283 M ops in only 170 shards, that may be something to consider(more shards?)

We can see the activity in the different months:

```
    coreadmin@CORE-01:~$ curl -X GET --silent 'http://localhost:9200/bitshares-2018-07/_count' | jq
    {
      "count": 34194488,
      "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
      }
    }
    coreadmin@CORE-01:~$ curl -X GET --silent 'http://localhost:9200/bitshares-2018-06/_count' | jq
    {
      "count": 28514130,
      "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
      }
    }
    coreadmin@CORE-01:~$ curl -X GET --silent 'http://localhost:9200/bitshares-2018-05/_count' | jq
    {
      "count": 29665610,
      "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
      }
    }
    coreadmin@CORE-01:~$ curl -X GET --silent 'http://localhost:9200/bitshares-2018-01/_count' | jq
    {
      "count": 19396703,
      "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
      }
    }
    coreadmin@CORE-01:~$ curl -X GET --silent 'http://localhost:9200/bitshares-2017-06/_count' | jq
    {
      "count": 10795239,
      "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
      }
    }
    coreadmin@CORE-01:~$ 
```    


As we can see, the current month(2018-07) already haves 34M  ops, more than any other month in the blockchain however 2018-06, 2018-05 ares also big ones.
Please note how the indexes are done only in 5 shards.(didn't researched sharding yet).

I can keep trying to improve the plugin, one of the things i have in mind is the threading that was suggested and can maybe make a difference but also i want to have feedback as i want to keep improving in other areas as `es_objects` and others and this is taking me too much time while ill maybe should focus more on the features than in the performance if this replaying time is acceptable. 

It seems there is still a bottleneck somewhere that i am not being able to identify but i don't want to get obsessed too much with it as long as it works.

Pinging some persons that i know are already running ES nodes: @xeroc , @clockworkgr , @Tydus, @zapata, etc.

Opinions are welcome.

**Comment by oxarbitrage** [comment]
For the record, month July of 2018 was huge with 133M of operations:

```
coreadmin@CORE-01:~$ curl --silent -X GET http://localhost:9200/bitshares-2018-07/_count | jq
{
  "count": 133879948,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  }
}
```

total chain in sync is at almost 450M ops:

```
coreadmin@CORE-01:~$ curl --silent -X GET http://localhost:9200/bitshares-*/_count | jq
{
  "count": 449663336,
  "_shards": {
    "total": 175,
    "successful": 175,
    "skipped": 0,
    "failed": 0
  }
}
coreadmin@CORE-01:~$ 
```

As a developer the time to sync is almost unacceptable, as a node operator that will do this just once maybe it is not that bad considering the amount of data.

**Comment by abitmore** [comment]
Fixed by #1260.

**Comment by Zapata** [comment]
[Elastic Search documentation has some tips](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html), this one in particular:

> Disable refresh and replicas for initial loadsedit
If you need to load a large amount of data at once, you should disable refresh by setting index.refresh_interval to -1 and set index.number_of_replicas to 0. This will temporarily put your index at risk since the loss of any shard will cause data loss, but at the same time indexing will be faster since documents will be indexed only once. Once the initial loading is finished, you can set index.refresh_interval and index.number_of_replicas back to their original values.

I didn't tested it myself.

**Comment by oxarbitrage** [comment]
thank you @Zapata . something very similar to this was tried , search for: 

> with a template, i added a 5 minutes refresh window and no replicas for all the bitshares-* indexes with(not possible to do this anymore from the config file in the last versions of ES)

in message: https://github.com/bitshares/bitshares-core/issues/1224#issuecomment-413392675

it is good to have the link document from where the idea came from, which is actually your link.

**Comment by Zapata** [comment]
I have compiled a few advices that can apply to our usage of ES. Needs to be tested.

- At index time:
-- [disable refresh and replicas](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html#_disable_refresh_and_replicas_for_initial_loads)
-- [disable _field_names](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-field-names-field.html#_disabling_literal__field_names_literal)
-- [disable swapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#setup-configuration-memory)
-- disable `_source` field (see [here](https://qbox.io/blog/maximize-guide-elasticsearch-indexing-performance-part-1))
-- disable `_all` field (see [here](https://qbox.io/blog/maximize-guide-elasticsearch-indexing-performance-part-1))
-- increase  `index.translog.flush_threshold_size` (see [here](https://qbox.io/blog/maximize-guide-elasticsearch-indexing-performance-part-2))
-- [use only keyword fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#_structured_search) 

 

- At query time:
-- Use filter context instead of query context (see [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html))
-- increase refresh interval
-- retrieve only required fields (use [stored_fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-stored-fields.html))
-- sort by `_doc` when order does not matter
