### ISSUE TITLE
Review and test something-for-nothing check

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#132]
_From @theoreticalbts on November 23, 2015 16:51_

EDIT:  TLDR: I believe we did think about this and the current code tries to implement (c), but I think the implementation may be buggy and/or untested. And even correctly implemented it may behave in a way which sometimes makes perverse decisions from an economic policy perspective.

Long version:  (end EDIT)

The `amount == 0` check [here](https://github.com/cryptonomex/graphene/blob/09855166a2eab59d03ad199ac308c856f6a72e9e/libraries/chain/db_market.cpp#L282-L296) is apparently testing for a something-for-nothing situation, whereby the quantization of trade leads to a fill logic which results in something-for-nothing trade.

We need to carefully analyze the trade and determine that this logic can only trigger for dust values.  Also, I think this logic is in the wrong place.

What needs to be done on this is:
- Clearly and carefully define the situation(s) which need(s) to be prevented.
- Clearly and carefully define the system's desired response to the situation.
- Provide robust set of unit tests which check the above definitions match the implementation.

_Copied from original issue: cryptonomex/graphene#460_

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on November 23, 2015 16:53_

The situation to be prevented is, roughly, when a something-for-nothing trade would occur due to quantization effects.  In this case, the desired response, roughly, is to cancel the order of the party who would receive nothing.

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on November 23, 2015 17:24_

The simple situation to handle is when an order is fully satisfied with a surplus balance.  E.g. if Alice is top-of-book buying 3 B for 99 A, and Bob enters an order to sell 3 B for 100 A, then Bob should be totally filled and become the new top-of-book; but he should be immediately cancelled as he has a zero quantity.
- Cancel orders whose "have" or "want" reaches zero as a result of trade (i.e. completely filled).

The more subtle problem is a quantization problem.  Say Alice has the existing top-of-book order which is matching Bob's incoming order.  Let `a/b` be Alice's order price after cancelling any common denominator.  Then a trade `a-for-b` satisfies Alice's order price exactly, and any smaller trade must have some premium or discount.

Define an `a-for-b` trade to be a _unit trade_.

If the matched volume is greater than or equal to `a` then at least one unit trade is possible.  After all such unit trades are completed, there will likely be some residue.

If the matched volume is smaller, the system must find trades that don't occur at Alice's exact price, but rather have some premium or discount to her exact price.  To be consistent with the definition of price [1], this premium / discount must be more favorable than Alice's price.  It must similarly match Bob's price.  This can lead to situations where no integer-valued trade can occur between Alice and Bob, even though their prices overlap.

It is tempting to simply rule that any order with an insufficient balance to perform a unit trade is subject to cancellation when matched.  However, the matched order may be a margin call, which cannot be cancelled.

We need to either cancel orders which nearly match a margin call, or walk (potentially unboundedly?) deep in the book in order to find a match which is capable of unit exchange.

[1] Price can be defined as "the least favorable exchange rate a party is willing to accept in trade."

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on November 23, 2015 22:22_

Here is an example:

Alice's order:  Sell CORE at $3  /  8, balance  1000000 CORE
Bob's order:   Buy CORE at $19 / 50, balance $10

Both assets have precision of 1, i.e. the order balances are 1000000 CORE-satoshis and 10 USD-satoshis repectively.

Alice is selling at $3/8 CORE = $0.375 / CORE and Bob is buying at $19 / 50 CORE = $0.38, so based on the price, Alice and Bob should match.

Bob's $10 / $0.38 ~ 26.3.  So 26.3 is the fewest CORE he is willing to accept (assuming that the meaning of "price" is "the least favorable exchange rate a party is willing to accept in trade").  Combined with the design restriction that satoshis are indivisible, in practice this means Bob will only accept 27 or more CORE for his $10.

But $10 / 27 gives a price smaller than $0.370 and $0.371, which is smaller than Alice's sale price of $0.375.  So neither party can fill this offer.

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on November 23, 2015 22:22_

Here are the possible solutions to the problem:
- (a) Fill someone at a less favorable exchange rate than the price they specified in their order.  Downside:  This violates the above definition of price; i.e. if a user enters a price intending the system to never sell below that price in any circumstance, the system will not always behave in a way which fulfills that user intent.
- (b) Keep both orders on the books.  Downside:  This complicates the matching algorithm, as now Alice might be able to match an order behind Bob's order.  Naive implementation would have potentially unbounded matching complexity; a more clever implementation might be possible but would require substantial design and testing effort.
- (c) Cancel an order.  This is complicated by the fact that an order such as a margin call cannot be cancelled.  Downside:  When there are margin calls happening, it seems perverse to delete a large order that's willing to fill them just because the lead margin call happens to fall in a narrow window which causes a rounding issue.  Also, orders cancelled by this mechanism cannot be refunded by #445.  Otherwise an attacker who wants to consume a lot of memory on all nodes could create a large number of orders, then trigger this case to cancel them all, getting their investment in deferred cancellation fees back without paying the cancel op's per-order fee as intended.
- (d) Require all orders to use the same denominator.  Altcoin exchanges and many real-world markets like the stock market solve this problem by specifying one asset as the denominator asset, specifying a "tick" which is the smallest unit of price precision, and requiring all prices to conform.  Downside:  Complicates the implementation of flipped market UI, may require re-working part of market GUI, reduces user flexibility, new asset fields required to specify precision, if `n` assets exist then `O(n^2)` markets could exist and we need to figure out how to determine the precision requirement for all of them.

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on November 23, 2015 22:24_

TLDR:  I believe we did think about this and the current code tries to implement (c), but I think the implementation may be buggy and/or untested.  And even correctly implemented it may behave in a way which sometimes makes perverse decisions from an economic policy perspective.

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on November 23, 2015 22:27_

Assigning to @bytemaster for analysis / opinion on what course of action to take.  In particular, I need to know if this is problem enough to be considered a blocker for the next release.

**Comment by vikramrajkumar** [comment]
_From @bytemaster on December 1, 2015 16:18_

The proper response is to cancel the dust order and do nothing to the order the dust order was attempting to match against.   

So if I have a large order to buy $100 worth of BTS, and someone tries to buy an amount of bts worth less than 0.0000 BitUSD from me, my order should stand and they should get canceled.

By definition all orders are for an amount greater than 0 (or they are removed/filled).

The order that would "receive nothing" is by definition paired against a dust order that will receive something (dust).  The dust order is what should be canceled, not the order that would receive nothing.

**Comment by vikramrajkumar** [comment]
_From @bytemaster on December 1, 2015 16:53_

Upon further review of the code and the math involved, it is not possible to construct a new order with a price and amount that would get matched with an existing order and trigger the existing order to be canceled. 

We have defined a dust order as one where

ORDER_PRICE \* ORDER_AMOUNT == 0

This is the point at which the unfilled portion of the order is smaller than the resolution of the orders price and thus should be refunded to the user.

**Comment by vikramrajkumar** [comment]
_From @svk31 on July 3, 2016 8:37_

There's a consistent issue with orders that are not perfectly match causing the left-over to execute at prices far above/below the actual prices of the original orders, and bypassing the orderbook completely. As an example, here's the market history for OBITS:BTS yesterday:

Price        OBITS     BTS         DATE
25.56522    0.0023  0.05880 7/2 20:30:57
29.28000    0.0005  0.01464 7/2 20:30:30
25.67381    0.0084  0.21566 7/2 19:43:18
27.40000    0.0004  0.01096 7/2 19:43:15
37.50000    0.0002  0.00750 7/2 19:42:54
25.64848    0.0033  0.08464 7/2 17:49:12
26.86111    0.0018  0.04835 7/2 17:48:57
27.90000    0.0010  0.02790 7/2 17:48:39
29.52000    0.0005  0.01476 7/2 17:48:21
26.76667    0.0003  0.00803 7/2 17:48:06
25.49850    80,790.9324 2,060,047.22548 7/2 17:47:45

Throughout this there was massive sell support at around 25 BTS/OBITS, but the dust orders executed well above this. I'm not sure if this deserves a new issue or if it fits with the problem described in this issue.

**Comment by vikramrajkumar** [comment]
_From @nmywn on July 3, 2016 23:3_

price                  bts            open.BTC  
0.00000353  0.00283 0.00000001  3/07 18:14:45   market OPEN.BTC : BTS
 0,00000001*0,00000353 = 0

but

price                 open.BTC         BTS
283,000.00000   0.00000001  0.00283 3/07 18:14:45   market BTS : OPEN.BTC

283000×0,00283 = 800,89

so ORDER_PRICE \* ORDER_AMOUNT == 0
is true only at one market?

Im not sure how its working just guessing.

**Comment by vikramrajkumar** [comment]
_From @pmconrad on July 30, 2016 9:21_

See also https://steemit.com/bitshares/@skriptroid/openledger-trade-engine-bug-or#@cyrano.witness/re-skriptroid-openledger-trade-engine-bug-or-20160729t095720645z

My conclusion is that the market engine is correct, and that what users are complaining about is merely a display issue. The UI displays the trade price as calculated from paid/received, which can be significantly different from bid/ask on low-volume orders.

A possible fix might be to somehow include the order price in market history entries and have the UI display that instead of the trade price.

**Comment by abitmore** [comment]
Seems unfixed. I'm now reopening this issue. We can also continue the discussions in #342.

**Comment by destenson** [comment]
I admit I should look more closely before commenting, but it seems to me that the issue is so longstanding because you're going about it all wrong. I think the order matching should not be done in bitshares-core at all and it should not modify details of orders to make them fill. The UI should create orders & and submit them, and the core should accept only perfectly-submitted orders, or reject them when a miscalculation due to a UI bug slips through. It is bad user experience, and as we've seen for quite some time, too error-prone for the UI to submit approximate orders. The UI should be providing the user with exact (and 100% accurate) details of the order as it will be filled, and if it doesn't, that's a bug that should be fixed, not worked-around.

**Comment by pmconrad** [comment]
The UI cannot know in advance how an order will be filled, because by the time the order arrives on the market, the market will have changed (or it can change). I'm sure this is also true for centralized exchanges.

Even if the UI could do the order matching, the core has to validate the UI submissions, and at the point you run into the same rounding issues that we are seeing now.

**Comment by destenson** [comment]
I apologize for coming into the discussion late and malinformed. I used the term "order matching" far too loosely. And I've probably conflated multiple issues. And, of course the matching needs to be done as close to the blockchain as possible.

What I meant to say is that when placing an order, the UI knows what currencies are involved, their smallest units, and how much the smallest unit of X/Y is for that market be. Then it should only ever enter orders with a size that's an integer multiple of the unit. Then when orders are matched, there would never be less than a unit of dust remaining.

The history of most pairs pairs are riddled with the tiniest transactions (some of which cause misleading spikes on the chart) that seem to happen when there's a little dust left over that should have been a part of the previous transaction or not at all.

**Comment by pmconrad** [comment]
> What I meant to say is that when placing an order, the UI knows what currencies are involved, their smallest units, and how much the smallest unit of X/Y is for that market be. Then it should only ever enter orders with a size that's an integer multiple of the unit.

That is already the case. In BitShares, limit orders are specified in the form "I want to sell X and I want to receive at least Y". Both X and Y are integral multiples of the units in question. The order price is derived from this as Y/X.

Problems arise when you try to match this against another order with a different price. See the 4th comment in this issue for an example.

More problems arise when an order is partially filled, because the leftover X' multiplied with the original price Y/X is likely not an integral multiple of Y's unit.

**Comment by abitmore** [comment]
Here comes the detailed rules:
* match in favor of taker, or say, match at maker price
* round down receiving amounts when possible
  * when matching two limit orders, round down the receiving amounts in favor of bigger order, or say, try to fill the smaller order
    * if the smaller order would get nothing after the round-down, cancel it
  * when matching a limit order with a call order, in favor of call order, round down receiving collateral amount
    * if the limit order would get nothing after the round-down, cancel it
  * when matching a settle order with a call order, in favor of call order, round down receiving collateral amount
    * if the settle order would get nothing after the round-down, give it 1 Satoshi (round up); after paid both side, check (and allow) if a black swan is triggered by the round-up
  * when globally settling, in favor of call order, round down receiving collateral amount
    * when the asset is not a prediction market, if a call order would pay nothing, let it pay 1 Satoshi (round up).

Take the 4th comment in this issue as an example:
* Alice's order: Sell CORE at `$3 / 8 = $0.375`, balance `1000000 CORE`
* Bob's order: Buy CORE at `$19 / 50 = $0.38`, balance `$10`

Process:
* If both orders are limit orders
  * If Alice's order is maker, use `$3 / 8` as match price; since Bob's order is smaller, round in favor of Alice's order, so Bob will get `round_down($10 * 8 CORE / $3) = round_down(26.67 CORE) = 26 CORE`, the effective price would be `$10 / 26 CORE = $0.3846`.
  * If Bob's order is maker, use `$19 / 50` as match price; since Bob's order is smaller, round in favor of Alice's order, so Bob will get `round_down($10 * 50 CORE / $19 = round_down(26.32 CORE) = 26 CORE`, the effective price would still be `$10 / 26 CORE = $0.3846`.
* If Alice's order is a call order, always round in favor of it, we get same results.

If we change the example to this:
* Alice's order: Buy CORE at `3 CORE / $8 = 0.375`, balance `$1000000`
* Bob's order: Sell CORE at `19 CORE / $50 = 0.38`, balance `10 CORE`

Process:
* If both orders are limit orders, we get same results as above
* If Bob's order is a call order, we should always round in favor of it, however, it should have a debt amount which is an integer, for example `$27`, then Alice would get
  * `round_down(27 * 3 / 8) = round_down(10.125) = 10 CORE` as a maker, or 
  * `round_down(27 * 19 / 50) = round_down(10.26) = 10 CORE` as a taker.

**Comment by pmconrad** [comment]
Problems with this approach:
* It can be ambiguous which order is "smaller" since you can't compare them directly. You can only compare order1.balance with order2.balance * price - but which price, and what do you do if order1.balance < order2.balance * price but order1.balance * price' > order2.balance?
* In your example, Bob pays a higher price than specified, which means he could receive less in total than he originally specified as min_to_receive.
* The rounding error can be significant (always think of whaleshares), i. e. much higher than the tx fees. In that case, the proposed behaviour could be exploited in favour of the taker.

**Comment by abitmore** [comment]
* the first rule written above is "match at maker price"
* I think it's OK to break it
* the makers should know the risks in advance and, accept them or avoid participating in such markets.

**Comment by abitmore** [comment]
For example, create a new asset MINNOWSHARES backed by WHALESHARES, with price 1 WHALESHARES : 1,000,000 MINNOWSHARES. Due to rounding up, settling one MINNOWSHARES will get the settler 1 WHARESHARES. This is stupid business. Don't short.

**Comment by abitmore** [comment]
Continuing the example above: after the force settlement, the position with least collateral can have zero collateral, so a black swan would be triggered at price `0`, all positions will be forced to closed and all collateral will be returned, remaining MINNOWSHARES would have nothing backed. The next question: will it be revived instantly?

**Comment by pmconrad** [comment]
My point about which order is smaller was meant to refer to your rule about rounding when matching two limit orders.

When matching call orders, IMO we should *always* round in favour of the call. If a settlement receives 0 collateral as a result, that's acceptable IMO, because the settlement price in unknown at the time when settlement is requested, so no guarantee is violated (within the range of rounding errors). This should keep the collateral > 0 as long as there is outstanding debt.

Breaking the min_to_receive limit is a no-go IMO. That's why it's called a "limit order".

**Comment by abitmore** [comment]
>My point about which order is smaller was meant to refer to your rule about rounding when matching two limit orders.
>> You can only compare order1.balance with order2.balance * price - but which price

The maker price.

> price in unknown at the time when settlement is requested

IMHO if a force settlement order would get nothing, it would break the compromise that "every smart coin is backed by something" which is unacceptable.

>Breaking the min_to_receive limit is a no-go IMO. That's why it's called a "limit order".

It's already broken now. The "rounding in favor of bigger order" rule is not new. It's mentioned by BM [above](https://github.com/bitshares/bitshares-core/issues/132#issuecomment-273344443). We have to make a compromise when the scenario described in the 4th comment in this issue occurs. IMHO "rounding in favor of bigger order" is a good compromise.

**Comment by pmconrad** [comment]
> IMHO if a force settlement order would get nothing, it would break the compromise that "every smart coin is backed by something" which is unacceptable.

Hm, what happens right now if you settle .0001 KRW (current feed price is 0.00358 BTS/KRW)?
We're still talking about a rounding issue and paying out 1 satoshi more or less collateral. Paying out 1 satoshi too much can bring us real trouble like you pointed out, because that could reduce collateral to 0 without paying back all the debt. Paying out 1 satoshi less is reasonable and much more safe IMO.

> It's already broken now. 

Is it? BM only talks about cancelling dust, not about rounding beyond the limit.

**Comment by abitmore** [comment]
>>IMHO if a force settlement order would get nothing, it would break the compromise that "every smart coin is backed by something" which is unacceptable.
>
>Hm, what happens right now if you settle .0001 KRW (current feed price is 0.00358 BTS/KRW)?
We're still talking about a rounding issue and paying out 1 satoshi more or less collateral. Paying out 1 satoshi too much can bring us real trouble like you pointed out, because that could reduce collateral to 0 without paying back all the debt. Paying out 1 satoshi less is reasonable and much more safe IMO.

Bottom line, paying something for nothing is unacceptable. If we can't reach consensus on this, we're unable to discuss further. Based on this, if there is a rounding to zero issue, we need to cancel an order, or keep the orders there and try later. Due to `"maximum_force_settlement_volume"`, we can't simply cancel a force settle order. Skipping the top order but matching the 2nd will make the situation much more complicated. To me, the clearest way here is to round up to 1 Satoshi.

>>It's already broken now.
>
>Is it? BM only talks about cancelling dust, not about rounding beyond the limit.

Yes. See the code in [database::match(...)](https://github.com/bitshares/bitshares-core/blob/2.0.171105a/libraries/chain/db_market.cpp#L311-L324) for example:
```
   if( usd_for_sale <= core_for_sale * match_price )
   {
      core_receives = usd_for_sale;
      usd_receives  = usd_for_sale * match_price; // round down, in favor of bigger order
   }
   else
   {
      usd_receives = core_for_sale;
      core_receives = core_for_sale * match_price; // round down, in favor of bigger order
   } 
   core_pays = usd_receives;
   usd_pays  = core_receives;
```
When the scenario described in the 4th comment of this issue occurs:
* Alice's order: Sell CORE at `$3 / 8 = $0.375`, balance `1000000 CORE`
* Bob's order: Buy CORE at `$19 / 50 = $0.38`, balance `$10`

Process:
* If Alice's order is maker, use `$3 / 8` as match price; since Bob's order is smaller, round in favor of Alice's order, so Bob will get `round_down($10 * 8 CORE / $3) = round_down(26.67 CORE) = 26 CORE`, the effective price would be `$10 / 26 CORE = $0.3846`.
* If Bob's order is maker, use `$19 / 50` as match price; since Bob's order is smaller, round in favor of Alice's order, so Bob will get `round_down($10 * 50 CORE / $19 = round_down(26.32 CORE) = 26 CORE`, the effective price would still be `$10 / 26 CORE = $0.3846`.

In any case, Bob won't get `27 CORE`, but only `26 CORE`, the effective price is always above the price he preferred. As I've said, we have to make a compromise here, rounding in favor of bigger order is better than cancelling one of them, also better than leaving both orders hanging in market.

**Comment by abitmore** [comment]
Done with #830. Closing.
