### ISSUE TITLE
what is the expected result of witness voting with num_witness=0

### ISSUE THREAD

**Issue by ihla** [bitshares/bitshares-core#1390]
I'd like to check if the following behaviour is as expected.  
What if the `num_witness`=0 while the `votes` includes some witness ids I am voting for. The comment in `struct account_options` says *Must not exceed the actual number of witnesses voted for in @ref votes* that is true in this case.  
That is also exactly what is checked in validate() method:  
```c++
void account_options::validate() const
{
   auto needed_witnesses = num_witness;
   auto needed_committee = num_committee;

   for( vote_id_type id : votes )
      if( id.type() == vote_id_type::witness && needed_witnesses )
         --needed_witnesses;
      else if ( id.type() == vote_id_type::committee && needed_committee )
         --needed_committee;

   FC_ASSERT( needed_witnesses == 0 && needed_committee == 0,
              "May not specify fewer witnesses or committee members than the number voted for.");
}
```  
  
It seeems to me, the votes are counted in at the maintenance even if the `num_witness` passed within the `account_options` was 0. Is it correct? The same likely applies also to the `num_committee`.

**Comment by pmconrad** [comment]
Yes, that's correct.

The decision *who* should be a witnesses is partially independent from the decision *how many* witnesses we should have.

For example, like this you can express a vote like "I think 1 witness would be enough. I'll vote for Alice, Bob and Charlie, because either one would do a good job, but I don't trust Dave and Eve."

It is not allowed to vote like "I think we need 3 witnesses. I'll vote for Alice.", because the chain expects you to be able to name three if you want three.

(Same for committee members of course.)

**Comment by abitmore** [comment]
By the way, https://github.com/bitshares/bitshares-core/blob/6218cdf1fcf5310cace81f86a35044ef6b42abec/libraries/chain/db_maint.cpp#L206-L207
```
 /// accounts that vote for 0 or 1 witness do not get to express an opinion on 
 /// the number of witnesses to have (they abstain and are non-voting accounts) 
```

**Comment by ihla** [comment]
as @abitmore has pointed out, the accounts voting for 0 and 1 witness count "abstain", technically speaking, their votes are excluded from the calculation of median witness count as can be seen here: https://github.com/bitshares/bitshares-core/blob/6218cdf1fcf5310cace81f86a35044ef6b42abec/libraries/chain/db_maint.cpp#L204

**Comment by ihla** [comment]
the question answered, can be closed
