### ISSUE TITLE
Update Copyright to 2020

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1524]
**User Story**
As the `BitShares DAC` we want `the copyright to reflect the current year` so that `our development efforts are respected`.

**Additional Context (optional)**
Impacts multiple branches:
<del>- [ ] `master` #1523 </del>
- [x] `develop` #1525 
<del>- [ ] `hardfork` #1526 </del>

**Comment by abitmore** [comment]
If it's a task of next release, one PR to develop branch is enough, since it will be merged into other branches later. If we want to have it in master branch before next release (which IMHO is not needed because we haven't contributed code to master in 2019 so no need to update license year there), please follow the document-change steps (aka Emergency Fix steps) listed in Git Flow.

**Comment by ryanRfox** [comment]
Yes, you are correct @abitmore we need only #1525 and it will propagate elsewhere. @xeroc provided a thoughtful comment https://github.com/bitshares/bitshares-core/pull/1525#issuecomment-459773071 for me to consider, so moving this to the next Feature Release.

**Comment by abitmore** [comment]
Done. #1525.
