### ISSUE TITLE
Unexpected behavior with low target ratio

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-core#1542]
If Target Ratio set less 1.75 then margin call order have low size. Only after full execution this order create new order with full size order as if target ratio equal 0.
Before full execution target order
![bug01](https://user-images.githubusercontent.com/6587277/51765591-3dee3180-20e9-11e9-934e-437022c4bd6e.PNG)
![bug02](https://user-images.githubusercontent.com/6587277/51765599-4181b880-20e9-11e9-960c-d039c1198b47.PNG)
after full execution target order
![image](https://user-images.githubusercontent.com/6587277/51765650-6aa24900-20e9-11e9-8dcd-a01f4c95b671.png)
![image](https://user-images.githubusercontent.com/6587277/51765678-7f7edc80-20e9-11e9-88cc-eb37b2767e73.png)

I think right behaviour - if target ratio less MCR then set it on MCR level or not provide ability set low target ratio.

**Comment by abitmore** [comment]
Current behavior is actually what you described. See https://github.com/bitshares/bsips/blob/master/bsip-0038.md#the-definition-of-target-collateral-ratio
> When the value is set but below MCR, use MCR.

So why in your screenshot the order's CR changed from 1.70 to 1.701? I guess the answer is because size of the matched limit order is too small. If you want to test the feature, try match it with a bigger limit order.

**Comment by akledirs** [comment]
Was sell ~19 gridcoin - this show in changed debt. Yes, later I sold more GRIDCOIN and I can't sell all - only such value that ratio encrease to 1.75. This not comfortly - order should show on sum needed for increasing to ratio 1.75

**Comment by abitmore** [comment]
Then it's a UI issue. Please report to https://github.com/bitshares/bitshares-ui.
