### ISSUE TITLE
Improve Protocol Library Build Process

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1568]
**User Story**
As a `developer` I want the `**protocol library** build system improved` so  we can `evaluate the benefits/viability of converting the remaining **bitshares-core** repository to Meson from CMake`.

**Additional Context (optional)**
Recommendation: initially create both build systems for the protocol library to allow for a direct side-by-side comparison at small scale, at which point a prediction for the advantages of Meson to be apparent.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by nathanhourt** [comment]
This issue was created to follow up #1506, and remove the protocol library from the main BitShares repo altogether once it was separated from the chain library.

This would be done primarily to support/encourage development of third party implementations of the BitShares core protocol, independent of the reference implementation. Since there is presently no project to do this, splitting off protocol from the main repo is not a priority.

Closing this issue due to lack of interest.
