### ISSUE TITLE
Docker Container should allow to specify the content of api-access file and config file via environmental variables

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#1605]
**User Story**
When deploying a bitshares container, I would like to be able to define the content of all files that i can usually provide via command line tools. The reason is that it is not trivial to copy files into a container prior to it being executed. The files that are commonly available are:

* config.ini
* api-access.json
* genesis.json (optional)

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [X] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Not sure how others are doing it, but IMO the most straightforward solution for this is to mount an external directory as the predefined `data-dir`. This is advisable anyway because you want the data dir to survive a container restart, and it can also contain all required config files.

Specifying secrets like witness block signing keys via environment variables (or command line arguments) is inadvisable anyway, for security reasons.

**Comment by xeroc** [comment]
closing this. peter is right, should be done with docker volumes instead
