### ISSUE TITLE
Clean up re-indexing logic

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#175]
_From @theoreticalbts on February 16, 2016 19:19_

Some of the reindexing stuff in `application.cpp` is wonky and doesn't re-write the version file, leading to an unnecessary re-index on next startup.

_Copied from original issue: cryptonomex/graphene#587_

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on February 23, 2016 15:48_

Progress, but doesn't work yet.

**Comment by oxarbitrage** [comment]
I was checking into this issue and i was not able to find the problem with the version file. 

From my testing, when the version file db_version is missing or when the content of the file is different than the constant `GRAPHENE_CURRENT_DB_VERSION` then the chain is replayed.

I made a test by manually changing the content of the db_version file from BTS2.9(current) to BTS2.8.

Restarting the node with this change will lead to replay with message:

`126936ms th_a       application.cpp:433           startup              ] Replaying blockchain due to version upgrade
`
In the reindex process, the current outdated db_version file is deleted and after the reindex is done the file is created again with the new GRAPHENE_CURRENT_DB_VERSION inside. The re-write is actually happening.

After that, i stopped the node with Ctrl-C only once and waited until the program exit clean. After a clean shutdown, at the moment of restarting there will not be reindex at all.

Reindex only happening when the shutdown was not clean or when the version of the database is different than the one in the db_version file.

This seems correct behavior to me.
