### ISSUE TITLE
where does impl::position<X, Types...>::pos initialized?

### ISSUE THREAD

**Issue by csquan** [bitshares/bitshares-core#1850]
in file:libraries/fc/include/fc/static_variant.hpp,where does impl::position<X, Types...>::pos initialized?

**Comment by csquan** [comment]
there are 3 position which  initialize pos = -1 or 0 or ++,but break point does not break,so is some other place?

**Comment by nathanhourt** [comment]
```c++
template<typename X, typename... Ts>
struct position;

template<typename X>
struct position<X> {
    static const int pos = -1;
};

template<typename X, typename... Ts>
struct position<X, X, Ts...> {
    static const int pos = 0;
};

template<typename X, typename T, typename... Ts>
struct position<X, T, Ts...> {
    static const int pos = position<X, Ts...>::pos != -1 ? position<X, Ts...>::pos + 1 : -1;
};
```

Hi, @csquan :) This is template metaprogramming, so it doesn't read like normal C++ code. It's manipulation of types, not values, done completely at compile-time, and is a purely functional sub-language within C++.

If you're not used to template metaprogramming, this code may be difficult to understand at first, but basically what's going on is that `position` is a metafunction (compile-time function) which takes a type X and a list of arbitrarily many types, and is recursively defined with two base cases:

 - `struct position<X>`: The list of types is empty (the only argument is `X`), in which case `X` is not in the list so it's position is -1
 - `struct position<X, X, Ts...>`: The list of types begins with `X` (same type as the one we're looking for), so the position of `X` is 0

Finally, there's the recursive call:
 - `struct position<X, T, Ts...>`: The list of types begins with `T` (not the same as `X`), so we throw `T` away and examine the rest of the list (`Ts...`) recursively. If the position of `X` in `Ts...` is -1, then it's not there, so it's not in the list `T, Ts...` either; otherwise, the position of `X` in `T, Ts...` is one plus the position of `X` in `Ts...`.

Does that clear it up for you?

**Comment by csquan** [comment]
yes，I got it,thank you for your answer.
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Nathan Hourt"<notifications@github.com>;
 发送时间: 2019年7月17日(星期三) 凌晨2:00
 收件人: "bitshares/bitshares-core"<bitshares-core@noreply.github.com>;
 抄送: "mars"<314588595@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [bitshares/bitshares-core] where does impl::position<X,Types...>::pos initialized? (#1850)

 

 template<typename X, typename... Ts> struct position; template<typename X> struct position<X> {     static const int pos = -1; }; template<typename X, typename... Ts> struct position<X, X, Ts...> {     static const int pos = 0; }; template<typename X, typename T, typename... Ts> struct position<X, T, Ts...> {     static const int pos = position<X, Ts...>::pos != -1 ? position<X, Ts...>::pos + 1 : -1; };
 
Hi, @csquan :) This is template metaprogramming, so it doesn't read like normal C++ code. It's manipulation of types, not values, done completely at compile-time, and is a purely functional sub-language within C++.
 
If you're not used to template metaprogramming, this code may be difficult to understand at first, but basically what's going on is that position is a metafunction (compile-time function) which takes a type X and a list of arbitrarily many types, and is recursively defined with two base cases:
  
struct position<X>: The list of types is empty (the only argument is X), in which case X is not in the list so it's position is -1
 
struct position<X, X, Ts...>: The list of types begins with X (same type as the one we're looking for), so the position of X is 0
 
Finally, there's the recursive call:
  
struct position<X, T, Ts...>: The list of types begins with T (not the same as X), so we throw T away and examine the rest of the list (Ts...) recursively. If the position of X in Ts... is -1, then it's not there, so it's not in the list T, Ts... either; otherwise, the position of X in T, Ts... is one plus the position of X in Ts....
 
Does that clear it up for you?
