### ISSUE TITLE
Update private testnet doc

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1861]
The default value of `required-participation` parameter in `witness` plugin is `33`, with this number, when starting a private testnet, the node won't produce blocks.

**Comment by cedar-book** [comment]
===============================================
-witness plugin options
     ===============================================
Enable block production, even if the chain is stale.
-enable-stale-production = false
 Percent of witnesses (0-100) that must be participating in order to produce blocks
-required-participation = 33
 ID of witness controlled by this node (e.g. "1.6.5", quotes are required, may specify multiple times)
-witness-id =
 Tuple of [PublicKey, WIF private key] (may specify multiple times)
-private-key = .....
//---------- (the above is from current config.ini)----------------

Why the default value is 33? 

What would be a recommendation for people who want to start a private testnet? 
 - enable-stale-production = false 
 - required-participation = 33 -->can they start with 0 first time?

**Comment by abitmore** [comment]
Yes, need to change `required-participation` to `0`.

**Comment by cedar-book** [comment]
As a quick note. Updated the information on this page's example [Configuration for Private Testnets](https://dev.bitshares.works/en/master/development/apps/node_config_example_private_testnet.html#configuration-for-private-testnets) and added a warning.

**Comment by oxarbitrage** [comment]
Added to https://github.com/bitshares/bitshares-core/wiki/private-testnet#starting-block-production

**Comment by abitmore** [comment]
Thank you.
