### ISSUE TITLE
return timestamp in get_order_book api call

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1908]
To get the timestamp of an order book the developer will have to make a separated query to get the head_block_time. This can be a different time than the order book he/she is getting.

A `timestamp` field can be added among the `bids` and the `asks` with timestamp at the moment of pulling the order book.

Coming from https://github.com/bitshares/bitshares-explorer-api/pull/64#discussion_r312581255

**Comment by abitmore** [comment]
Please be aware that
1. order book of normal API nodes usually contains unconfirmed data due to pending transactions, thus it can change when being included in a block;
2. even if it's included in a block, before the block become irreversible, the state can change due to chain reorganization;
3. order book of delayed_node usually doesn't make sense for traders.

So a timestamp especially `head_block_time` doesn't really make sense. IMHO you can just return a local time.

**Comment by oxarbitrage** [comment]
Makes sense to me.
