### ISSUE TITLE
broadcast_transaction params how set

### ISSUE THREAD

**Issue by boy-good** [bitshares/bitshares-core#2053]
broadcast_transaction rpc for cli_wallet
how to set params? please help me.

**Comment by pmconrad** [comment]
`broadcast_transaction` expects a complete signed transaction as its only parameter.

If you already have a complete signed transaction you can as well use the `broadcast_transaction` call in the node API, bypassing `cli_wallet`.

If your question is how to *create* a complete signed transaction - that's difficult. I suggest you use one of the available client libraries, like https://github.com/bitshares/python-bitshares or https://github.com/bitshares/bitsharesjs . Then you don't have to worry about the details of this call.

Another option would be to use the other calls of `cli_wallet` in order to let `cli_wallet` create, sign and broadcast the actual transaction that you want to perform.

**Comment by boy-good** [comment]
@pmconrad Thanks much. I want to use Java to build transaction,sign and push tx without node or wallet file. How to do it,can you help me. So i try to use graphenej like https://github.com/computationalcore/graphenej. but it no success.T_T

**Comment by pmconrad** [comment]
You'll have to provide a more specific problem description if you want help. What did you try, what worked, what didn't?

I'm not familiar with graphenej myself, but I suppose that it's working when used correctly.

**Comment by boy-good** [comment]
@pmconrad 
![image](https://user-images.githubusercontent.com/39320533/68943224-8811e200-07e5-11ea-9d02-efa99c9a9110.png)

{"expiration":"2019-11-15T12:21:08","signatures":["1c26fb6f50091e3dfad6a3eac5fb6572262a1c85af985c7f15f2880f98bbbce01742cc98b44104daa6e2271ade226095f5ec91b8dc990164ccf3fff36e3ca6a42a"],"operations":[null],"extensions":[],"ref_block_num":52885,"ref_block_prefix":12}

![image](https://user-images.githubusercontent.com/39320533/68943262-a7107400-07e5-11ea-8113-a967986ab72b.png)

I try sign transaction and check it.But when toJsonString,the Operations is null. I debug it has one.
I dont know why and it maybe difficult to tell. T_T
Had you make transfer for BTS with Java Code? Thank you so much.Nice!

**Comment by pmconrad** [comment]
Like I said, I'm not familiar with the library. The "null" operations is definitely wrong.

According to the screenshot, the transaction contains one operation. Somewhere along the way it is serialized as `null`. I suggest you use a debugger to see what happens internally.

If you don't make progress, your best bet might be to ask in the BitsharesDEV telegram channel.

Closing here because it's not a core problem.

**Comment by boy-good** [comment]
@pmconrad  OK. Thank you very much. I had try again.
