### ISSUE TITLE
Implement BSIP 74: Margin Call Fee Ratio

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#2129]
This issue is to track the ***implementation*** of [BSIP 74](https://github.com/bitshares/bsips/blob/master/bsip-0074.md).

**Impacts**
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [X] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context**
Discussion about the BSIP itself can be found [here](https://github.com/bitshares/bsips/issues/164). This issue is to discuss implementation details.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
The spirit is "the call order gets charged" but not the limit order gets charged, although technically it's almost the same thing but with a shift on price.

**Comment by shulthz** [comment]
This fee must can be shared a part of it (e.g. like 20%) to the margin call buyer which can be decided by the asset owner.
These shared fees must be continually unlocked during a vesting period like 48 hours.
This will encourage the buyer to eat the margin call, it's a very important part.

**Comment by jmjatlanta** [comment]
> This fee must can be shared a part of it (e.g. like 20%) to the margin call buyer which can be set by the asset owner.
> These shared fees must be continually unlocked during a vesting period like 48 hours.
> This will encourage the buyer to eat the margin call, it's a very important part of this BSIP.

I do not see these requirements in the BSIP specifications. Was it agreed and voted upon elsewhere?

**Comment by shulthz** [comment]
> 
> 
> > This fee must can be shared a part of it (e.g. like 20%) to the margin call buyer which can be set by the asset owner.
> > These shared fees must be continually unlocked during a vesting period like 48 hours.
> > This will encourage the buyer to eat the margin call, it's a very important part of this BSIP.
> 
> I do not see these requirements in the BSIP specifications. Was it agreed and voted upon elsewhere?

I have give these requirements long times ago, but the author maybe didn't understand the spirit of this BSIP.

This BSIP have two main aims：
1. The margin call (with more lower MSSR) will not destroy the depth and price of DEX market like before;
2. The shared fees (with locked time) will encourage the buyers to eat the margin call:
   The shared fees  (with locked time) will not be exploited by the leveraged market of CEX any more;
   The shared fees (with locked time)  will not affect the depth and price of CEX market largely;
   It can instead of MSSR largely.

**Comment by bitcrab** [comment]
@jmjatlanta please ignore comments from @shulthz and work based on the BSIP itself.

**Comment by shulthz** [comment]
> 
> 
> @jmjatlanta please ignore comments from @shulthz and work based on the BSIP itself.

Don't act so stupid @bitcrab , you didn‘t understand this issue, and please know this BSIP come from which issue!

I even didn't want to talk about this with you, what you want is just charge fees, other thing you even didn't have the ability to realize.

**Comment by bitcrab** [comment]
> I even didn't want to talk about this with you, what you want is just charge fees, other more deep thing you even didn't have the ability to realize.

who are you? who cares the idea of a spammer? who want to talk this with you?
the BSIP work has its own process, now the BSIP74 document is ready and the programmers need to work based on it, surely everyone can discuss here, but not everyone can redefine the BSIP. please stop creating confusion.

**Comment by shulthz** [comment]
> 
> 
> > I even didn't want to talk about this with you, what you want is just charge fees, other more deep thing you even didn't have the ability to realize.
> 
> who are you? who cares the idea of a spammer? who want to talk this with you?
> the BSIP work has its own process, now the BSIP74 document is ready and the programmers need to work based on it, surely everyone can discuss here, but if you want to change the BSIP, you need to follow the process to create PR and request approval. please stop creating confusion.

This BSIP stolen the idea from the “spammer”, this BSIP also follow the issue, so i am the “spammer”！

So, who is the plagiarist and who are you？who should shame on this？

**Comment by shulthz** [comment]
This BSIP come from my issue, so i understand it more thorough than others, if just want to charge fees, we will didn't need this BSIP.
We spend money and time to develop a BSIP, not just for a little fees, we use it to build a more healthy defi market, to stop a kind of loop.

If just want to charge fees, this BSIP is failure, this BSIP shouldn't be exist, i will feel shame as it come from my issue.

**Comment by MichelSantos** [comment]
@dls-cipher @abitmore 

The development of BSIP74 required extensive iterations because the original specifications were sometimes _ambiguous, incomplete, or incompatible_ with all of the market situations and subtleties that are handled by the DEX mechanics.  These high-level and low-level problems were identified through a series of development pushes which are documented in discussions during the [first code pull request](https://github.com/bitshares/bitshares-core/pull/2130) which continued during the creation of the [second version of the specifications](https://github.com/bitshares/bsips/pull/273) and continued further during the development towards the second version of the specifications.

A brief description of how margin calls are handled will provide some context of the encountered issues.  Margin calls go through a two-step process that involves (1) matching a margin call against counter-offers on the order books, and (2) filling the margin call against the counter-offer.  Both the matching process and filling process depends on such things as the "match price" and the "fill price".  However those prices are highly dependent on other factors that were not addressed.

The development identified problems _with the matching process_ in the original specifications:

- the matching process was not addressed at all

- the matching process needed to be handled differently between maker and taker margin calls because the match price is different

- the match price also depends on the new margin call fee


The development also identified problems _with the filling process_ in the original specifications:

- the payer of the margin call fee was not identified

-  the new margin call fee ratio (MCFR) _may be incompatible_ with other parameters such as the maximum short squeeze ratio (MSSR)

- the fill price differs between maker and take margin calls due to [BSIP-32: "Always Match Orders At Maker Price"](https://github.com/bitshares/bsips/blob/master/bsip-0032.md)

- the filling process must account for target collateral ratios, [BSIP-38: "Add target collateral ratio option to short positions"](https://github.com/bitshares/bsips/blob/master/bsip-0038.md), which cannot naively use the match price because it must account for the new margin call fee


All of these problems have been fully defined and subsequently developed.  A new pull request will be submitted later today with the code and unit tests.

A third version of the BSIP74 specifications, which summarizes the resolved requirements, will also be submitted afterwards in a new pull request.

**Comment by abitmore** [comment]
@MichelSantos thank you for the detailed info. Looking forward to the new commits.

**Comment by abitmore** [comment]
Done via #2180.
