### ISSUE TITLE
Default for amount of open orders returned

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-core#2165]
**User Story**
As a `power trader` I want `to be able to use any public API` without `being castrated in my trading`.

The new pagination in full account API is too strict. We went from unlimited to returning a 100. I suggest to set the default to 500. This will only affect a handfull of users, but those users are especially important. This default can be re-evaluated once proper lazy loading is availble for all UIs.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by bangzi1001** [comment]
UI doesn't show more than 100 open orders for users
https://github.com/bitshares/bitshares-ui/issues/3248

**Comment by abitmore** [comment]
It was expected that UI would adapt to core changes in a few months. But it has been 10 months since the release of the `get_full_accounts` API change. Another API `get_account_limit_orders` which is more suitable for UI to call in the exchange page was released even earlier (in year 2018). There are a lot of things for UI to improve, rather than waiting forever.

Ideally power traders should run (or fund) their own nodes to support the decentralization of the network, but not only rely on free public API nodes. They can do whatever with their own nodes.

BTW public API nodes are free to update their servers parameters to fit users' needs.

**Comment by abitmore** [comment]
Fixed by #2190.
