### ISSUE TITLE
Plan B for upcoming chain forking

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2239]
**User Story**

A big part in the community, namely Cn-vote Union, announced a patch to the bitshares-core software in the forum along with actions they will take in the days after the announcement. A link to the announcement is [here](https://bitsharestalk.org/index.php?topic=32560), A link to the patch is [here](https://github.com/bitshares-cnvote/bitshares-core/compare/349e0061300d3e65a3e3040276c321b76069e44f...master). As of writing, certain actions have been taken by the Union, and likely there will be more actions.

It is likely that there will be a chain forking event a few minutes after `Thursday, August 20, 2020 13:55:00 UTC` (`2020-08-20T13:55:00Z`). In the best-case scenario, there will exist two major forks ("the current chain" and "the cn-vote chain"), and both forks will continue growing smoothly after the event. In the worst-case scenario, "the current chain" will stop growing after the event, regardless of whether other forks will survive.

As a user I would like to have a plan B so that "our chain" will continue growing no matter what, although it is possible that we will never need to execute it.

Technical speaking, if the current chain stops and restarts, it is no longer exactly the same one, but a variant, or say a new fork. So having a plan B essentially means to be prepared to "fork away".

Here are some factors that I've thought of:

1. options about timing:

1a. Fork away at the same time or before the time when the cn-vote patch takes effect.
  - Pros: "our chain" will not be affected by other forks; the plan is relatively easy to execute.
  - Cons: it is not exactly a "plan B", but a proactive action plan. It will probably create a new fork which is unnecessary, in other words, it will probably cause 3 forks growing at the same time.

1b. Fork away only when serious chain participation issues occur after the cn-vote patch took effect.
  - Pros: it is exactly a plan B and possibly never need to be executed.
  - Cons: there will be a period that the chain is unstable. To shorten the period, greater efforts on collaboration are required.

2. new BP protocol. It means to select a different set of block producers to grow the chain. Options:

2a. Temporarily set a fixed list of block producers until further actions.
  - Pros: easy to understand and not hard to make the list;
  - Cons: further actions are required.

2b. Adopt rules that can not be easily impacted by irresponsible voting behaviors, essentially, redefine who have the right to vote and how much voting weight they have.
  - Pros: potentially one fix for all;
  - Cons: probably requires greater efforts to find a good rule-set and to implement it.

Personally I would prefer 1b and 2b.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Comment by shulthz** [comment]
Who own the name？

**Comment by syalon** [comment]
2b is also very difficult to implement, and it is expected that there will still be various disputes.

**Comment by bitsharescrude** [comment]
Firstly if CN-VOTE chain is supported by more witnesses, suppose all the witnesses go to the CN-VOTE chain, that means the chain may stop fxning so all we need are witnesses who will continue to validate the new protocol, my suggestion is to implement number 2a and 2b if possible. Forking is not really the issue, the issue is validation.

**Comment by shulthz** [comment]
I don't think 1b is a good option, as it abandoned these witness which didn't support the cn-vote patch.

"when serious chain participation issues occur"
No one will know when is how long, maybe most of people will go away.

I prefer to 1a. 2a, then 2b.

As after 1a. cn-vote still will be the biggest Proxy, so it needs 2a. to fix this problem, after fix this problem, then can execute 2b. or wait the 60 days until the new rules affect.

In my opinion, do it or not do it, if we choose to do it, then do it as soon as possible, don't have any illusions.

**Comment by technologiespro** [comment]
I wonder what percentage of active witnesses have accepted the unofficial cn-vote patch?

At least 4 gateways are not in ui and do not know about updating the cn-vote, 
because most use the official repository and the official forum.

Because I have not seen the cn-vote patch in the official repositories, it turns out that this will be the new coin with a community that has its own interest other than the official one.

If the cn-vote wants to completely control the coin, I think first need:
-  to create a website 
- register this coin ticker in the coinmarketcaps
- add ui
- add documentation
- create forum community
- create gateways with listed coins + communities
- the blockexplorer
- have enough qualified developers
- build infrastructure
- get coin listing on exchanges

Maybe I'm wrong, but as far as understand, all that cn-vote has are lot votes
Gateways with their communities of listed coins cannot work in 2 chains. I hope they understand this? or not?
High concentration of capital does not guarantee technological growth without infrastructure.

**Comment by pluswave** [comment]
we can split BPs in to 4 categories:

1. all nodes are with cn-vote patch.
2. all nodes are without cn-vote patch.
3. some nodes applied cn-vote patch, some not. The active producing node is with the patch .
4. some nodes applied cn-vote patch, some not. The active producing node is without the patch.

for active BPs who voted in the HardFork time ( 2020-08-20 13:55:00 UTC), 
  if all are 1 or 3 (case A), then cn-vote will work; 
  if all are 2 or 4(case B), then nothing changes. 
  if 50% is in 1 or 3 (case C), then ? 
  if 80% is in 1 or 3 (case D), then ?
  if 80% is in 2 or 4 (case E), then ?

other than BPs, there are many API nodes. from the cn-vote declaration, they don't let any API nodes apply the patch. then there will be a interesting thing : if in case A, the chain will upgrade to cnvote version, but all API nodes will stuck.

**Comment by sschiessl-bcp** [comment]
1b would be most straightforward imho, and also inevitable since it is the choice that happens if nothing is done before 20th

**Comment by shulthz** [comment]
>
if in case A, the chain will upgrade to cnvote version, but all API nodes will stuck.

That is in the case, so i think 1a. is the first step and choice, lower the influence to API node and exchange.

**Comment by liondani** [comment]
I agree with:
"1b. Fork away only when serious chain participation issues occur after the cn-vote patch took effect." and hope there is no need for a fork becausemajority will not install the patch.

**Comment by bue-twitter** [comment]
> I agree with:
> "1b. Fork away only when serious chain participation issues occur after the cn-vote patch took effect." and hope there is no need for a fork becausemajority will not install the patch.

latest update :  around 12/19 are going to install cn-vote patch.

**Comment by shulthz** [comment]
If the feed price is safe on this event?

**Comment by dls-cipher** [comment]
Both as individual user/contributor and on behalf of Move Institute, we would be supporting:

1b as a quick and **temporary** solution that will keep our chain available to gateways and 3rd parties listing/using BTS token, until 2b is done and deployed. 



> > I agree with:
> > "1b. Fork away only when serious chain participation issues occur after the cn-vote patch took effect." and hope there is no need for a fork becausemajority will not install the patch.
> 
> latest update : around 12/19 are going to install cn-vote patch.

For 1b, I would be suggesting that witnesses willing to run software from our/official/original GitHub repository post here their participation decision. 

We have to be very careful with one thing. If for example AEX supports their patch and Poloniex ours, CNVOTE (as any other user of this chain) will have small window of opportunity to cash out double. 

We also have to provide 1b solution and witness list ASAP in order to restore proper feeds on bitassets were RUBLE and EUR are currently in a problem. I also suggest we do the activation prior to theirs. 

Better safe then sorry.

Chee®s

**Comment by shulthz** [comment]
A super proxy appeared, so, 2b? or 2a?

**Comment by abitmore** [comment]
IMHO (so far) no need to execute plan B if there is no serious chain stability issue.

**Comment by abitmore** [comment]
FWIW news about a new chain and airdropping from cn-vote (in Chinese): http://btsgh.com/?p=293 .

**Comment by shulthz** [comment]
> 
> 
> IMHO (so far) no need to execute plan B if there is no serious chain stability issue.

If cn-vote quickly change most of the witness to cn-vote witnee on the original chain in 9.10, what will happen?

I don't believe cn-vote didn't have other purpose for this huge vote buying, maybe we should see what alt will do.
