### ISSUE TITLE
Uninstall light client does not remove "personal info"

### ISSUE THREAD

**Issue by brekyrself** [bitshares/bitshares-core#227]
Win10 x64

When uninstalling the light client and clicking "remove also my BitShares2-light personal data" does not seem to remove my personal wallet file.  Upon installing a new version I do not have to load my wallet file, it's already showing up.

**Comment by oxarbitrage** [comment]
issue was replicated and fixed. the problem was on file electron/resources/windows/installer.nsi line 157 where the code to uninstall appdata folder is present.

NSIS LOCALAPPDATA variable don't have the path to roaming folder where bitshares ui install personal data. Also variable ${name} does not have the correct name of the folder so this was changed to ${productName}.

this worked fine.

**Comment by kenCode-de** [comment]
https://github.com/bitshares/bitshares-ui/pull/82
