### ISSUE TITLE
Dropped 7252 blocks from after the gap(resolved)

### ISSUE THREAD

**Issue by lanhaoxiang** [bitshares/bitshares-core#290]
Hi, 

We are starting our own chain forked from bitshares-core in our testnet, there are  only 2 witness node,  but it seems the 2 nodes will missing the same block  sometimes, could anyone show us why would the case happen, and how it could be resolved.  Would it help if we start more than 11 nodes?

Logs:

root@myserver:~/opt/bbc# ./programs/witness_node/witness_node 
2033263ms th_a       main.cpp:121                  main                 ] Error parsing logging config from config file /root/opt/bbc/witness_node_data_dir/config.ini, using default config
2033263ms th_a       witness.cpp:88                plugin_initialize    ] witness plugin:  plugin_initialize() begin
2033264ms th_a       witness.cpp:99                plugin_initialize    ] Public Key: BBC6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2033264ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
2033266ms th_a       application.cpp:452           startup              ] Detected unclean shutdown. Replaying blockchain...
2033266ms th_a       application.cpp:331           operator()           ] Initializing database...
2033271ms th_a       db_management.cpp:51          reindex              ] reindexing blockchain
2033271ms th_a       db_management.cpp:104         wipe                 ] Wiping database
2033273ms th_a       db_management.cpp:170         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"index.hpp","line":111,"method":"get","hostname":"","thread_name":"th_a","timestamp":"2017-05-26T02:33:53"},"format":"maybe_found != nullptr: Unable to find Object","data":{"id":"2.1.0"}}]}
2033278ms th_a       object_database.cpp:87        wipe                 ] Wiping object database...
2033284ms th_a       object_database.cpp:89        wipe                 ] Done wiping object databse.
2033284ms th_a       object_database.cpp:94        open                 ] Opening object database from /root/opt/bbc/witness_node_data_dir/blockchain ...
2033286ms th_a       object_database.cpp:100       open                 ] Done opening object database.
2033295ms th_a       db_debug.cpp:85               debug_dump           ] total_balances[asset_id_type()].value: 0 core_asset_data.current_supply.value: 1000000000000000 
2033297ms th_a       db_management.cpp:128         open                 ] last_block->id(): 000099ab1af477385c881d1df992dc7ccb792e2d last_block->block_num(): 39339 
2033297ms th_a       db_management.cpp:129         open                 ] head_block_id(): 0000000000000000000000000000000000000000 head_block_num(): 0 
2033297ms th_a       db_management.cpp:65          reindex              ] Replaying blocks...
   12.71%   5000 of 39339   
   25.4201%   10000 of 39339   
   38.1301%   15000 of 39339   
   50.8401%   20000 of 39339   
   63.5502%   25000 of 39339   
   76.2602%   30000 of 39339   
2033663ms th_a       db_management.cpp:73          reindex              ] Reindexing terminated due to gap:  Block 32087 does not exist!
2053106ms th_a       db_management.cpp:87          reindex              ] Dropped 7252 blocks from after the gap
2053107ms th_a       db_management.cpp:99          reindex              ] Done reindexing, elapsed time: 19.80972099999999969 sec
2053150ms th_a       application.cpp:190           reset_p2p_node       ] Adding seed node 192.168.1.118:2776
2053150ms th_a       application.cpp:190           reset_p2p_node       ] Adding seed node 192.168.1.119:2776
2053156ms th_a       application.cpp:205           reset_p2p_node       ] Configured p2p node to listen on 192.168.1.118:2776
2053158ms th_a       application.cpp:280           reset_websocket_serv ] Configured websocket rpc to listen on 0.0.0.0:28090
2053158ms th_a       witness.cpp:122               plugin_startup       ] witness plugin:  plugin_startup() begin
2053158ms th_a       witness.cpp:127               plugin_startup       ] Launching block production for 11 witnesses.
2053158ms th_a       witness.cpp:138               plugin_startup       ] witness plugin:  plugin_startup() end
2053158ms th_a       main.cpp:179                  main                 ] Started witness node on a chain with 32086 blocks.
2053158ms th_a       main.cpp:180                  main                 ] Chain ID is 40be73b8c0a5d2ce760e42bc906ae0af2c00975eda07ff99e1405fe1a543432b
2054000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2055000ms th_a       witness.cpp:177               block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
    {"item->num":32087,"head":39339,"max_size":9}
    th_a  fork_database.cpp:80 _push_block

    {"new_block":{"previous":"00007d56a548ba8c61b40811005fa6c247b76f63","timestamp":"2017-05-26T02:34:15","witness":"1.6.2","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f53b179a4b8fb6aebcb56cd7380eb52d90a838580d553ed5744a9092421d09367333197c916db14bd88879b2b6867269a28ace78cd69322626e0111cdb8d9245b","transactions":[]}}
    th_a  db_block.cpp:208 _push_block

    {"witness_id":"1.6.2"}
    th_a  db_block.cpp:419 _generate_block

    {}
    th_a  db_block.cpp:317 generate_block
2055000ms th_a       witness.cpp:208               block_production_loo ] exception prodcing block
2056000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2057000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2058000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2059000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2060000ms th_a       witness.cpp:177               block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
    {"item->num":32087,"head":39339,"max_size":9}
    th_a  fork_database.cpp:80 _push_block

    {"new_block":{"previous":"00007d56a548ba8c61b40811005fa6c247b76f63","timestamp":"2017-05-26T02:34:20","witness":"1.6.3","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f305d43e53a9aedc464c5f4be020b2b84a90c42bbdbc5b4638ea96e5602b509464a796e6ff142b2734278e1567f0b98c6bfc4aa7c81cb60ac6b03e0dc19d24737","transactions":[]}}
    th_a  db_block.cpp:208 _push_block

    {"witness_id":"1.6.3"}
    th_a  db_block.cpp:419 _generate_block

    {}
    th_a  db_block.cpp:317 generate_block
2060000ms th_a       witness.cpp:208               block_production_loo ] exception prodcing block
2061000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2062000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2063000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2064000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2065000ms th_a       witness.cpp:177               block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
    {"item->num":32087,"head":39339,"max_size":9}
    th_a  fork_database.cpp:80 _push_block

    {"new_block":{"previous":"00007d56a548ba8c61b40811005fa6c247b76f63","timestamp":"2017-05-26T02:34:25","witness":"1.6.8","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"2024b2db8b631cbb030cc4b211920432d5da244066f6f8b99293a7c1021d6671a57cadc1181e4bafbdf71472d4b5284ca6ef1aa5f7634a6fa7043d95cefcdaf623","transactions":[]}}
    th_a  db_block.cpp:208 _push_block

    {"witness_id":"1.6.8"}
    th_a  db_block.cpp:419 _generate_block

    {}
    th_a  db_block.cpp:317 generate_block
2065000ms th_a       witness.cpp:208               block_production_loo ] exception prodcing block
2066000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2067000ms th_a       witness.cpp:202               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2067093ms asio       main.cpp:170                  operator()           ] Caught SIGINT attempting to exit cleanly
2067094ms th_a       main.cpp:183                  main                 ] Exiting from signal 2
2067095ms th_a       db_management.cpp:170         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":43,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2017-05-26T02:34:27"},"format":"prev: poping block would leave head block null","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":438,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2017-05-26T02:34:27"},"format":"","data":{}}]}
2067122ms p2p        thread.cpp:246                exec                 ] thread canceled: 9 canceled_exception: Canceled

    {}
    p2p  thread_d.hpp:461 start_next_fiber
2067123ms th_a       db_management.cpp:170         close                ] Database close unexpected exception: {"code":3070001,"name":"pop_empty_chain","message":"there are no blocks to pop","stack":[{"context":{"level":"error","file":"db_block.cpp","line":430,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2017-05-26T02:34:27"},"format":"there are no blocks to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":438,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2017-05-26T02:34:27"},"format":"","data":{}}]}
root@myserver:~/opt/bbc# ./programs/witness_node/witness_node 
2069678ms th_a       main.cpp:121                  main                 ] Error parsing logging config from config file /root/opt/bbc/witness_node_data_dir/config.ini, using default config
2069678ms th_a       witness.cpp:88                plugin_initialize    ] witness plugin:  plugin_initialize() begin
2069678ms th_a       witness.cpp:99                plugin_initialize    ] Public Key: BBC6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2069678ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
2069679ms th_a       object_database.cpp:94        open                 ] Opening object database from /root/opt/bbc/witness_node_data_dir/blockchain ...
2069692ms th_a       object_database.cpp:100       open                 ] Done opening object database.
2069700ms th_a       application.cpp:190           reset_p2p_node       ] Adding seed node 192.168.1.118:2776
2069700ms th_a       application.cpp:190           reset_p2p_node       ] Adding seed node 192.168.1.119:2776
^C
root@myserver:~/opt/bbc# ./programs/witness_node/witness_node 
2082176ms th_a       main.cpp:121                  main                 ] Error parsing logging config from config file /root/opt/bbc/witness_node_data_dir/config.ini, using default config
2082176ms th_a       witness.cpp:88                plugin_initialize    ] witness plugin:  plugin_initialize() begin
2082176ms th_a       witness.cpp:99                plugin_initialize    ] Public Key: BBC6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2082176ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
2082176ms th_a       application.cpp:452           startup              ] Detected unclean shutdown. Replaying blockchain...
2082176ms th_a       application.cpp:331           operator()           ] Initializing database...
2082178ms th_a       db_management.cpp:51          reindex              ] reindexing blockchain
2082178ms th_a       db_management.cpp:104         wipe                 ] Wiping database
2082178ms th_a       db_management.cpp:170         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"index.hpp","line":111,"method":"get","hostname":"","thread_name":"th_a","timestamp":"2017-05-26T02:34:42"},"format":"maybe_found != nullptr: Unable to find Object","data":{"id":"2.1.0"}}]}
2082180ms th_a       object_database.cpp:87        wipe                 ] Wiping object database...
2082186ms th_a       object_database.cpp:89        wipe                 ] Done wiping object databse.
2082186ms th_a       object_database.cpp:94        open                 ] Opening object database from /root/opt/bbc/witness_node_data_dir/blockchain ...
2082186ms th_a       object_database.cpp:100       open                 ] Done opening object database.
2082189ms th_a       db_debug.cpp:85               debug_dump           ] total_balances[asset_id_type()].value: 0 core_asset_data.current_supply.value: 1000000000000000 
2082201ms th_a       db_management.cpp:58          reindex              ] !no last block
2082201ms th_a       db_management.cpp:59          reindex              ] last_block:  
2082203ms th_a       application.cpp:190           reset_p2p_node       ] Adding seed node 192.168.1.118:2776
2082204ms th_a       application.cpp:190           reset_p2p_node       ] Adding seed node 192.168.1.119:2776
^C
root@myserver:~/opt/bbc# ./programs/witness_node/witness_node

**Comment by zhuliting** [comment]
I met the same problem once,  when the connection from remote server is lost,  and restart witness_node again. Please anyone can help explaining why ?

**Comment by abitmore** [comment]
This is interesting. We've met this before. Sometimes a generated block doesn't get stored to the database, but the nodes will still build blocks after it. It usually happens when there is a fork. The real reason is still unknown. Best if we can find a stable way to reproduce it

**Comment by zhuliting** [comment]
@abitmore 


when replaying block, I have met  a strange block,  which has a previous bock_id"0000000000000000000000000000000000000000" and witness_id"1.6.0" , in my config.ini, my witness_id starts begins at "1.6.1",  and I don't know how this block is generated, here is the log:

1282031ms th_a       main.cpp:121                  main                 ] Error parsing logging config from config file /Users/albert/bitshares-core-core/witness_node_data_dir/config.ini, using default config
1282032ms th_a       witness.cpp:88                plugin_initialize    ] witness plugin:  plugin_initialize() begin
1282034ms th_a       witness.cpp:99                plugin_initialize    ] Public Key: BTSC6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
1282034ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
1282034ms th_a       application.cpp:453           startup              ] Detected unclean shutdown. Replaying blockchain...
1282034ms th_a       application.cpp:332           operator()           ] Initializing database...
1282037ms th_a       db_management.cpp:51          reindex              ] reindexing blockchain
1282037ms th_a       db_management.cpp:116         wipe                 ] Wiping database, data_dir /Users/albert/bitshares-core-core/witness_node_data_dir/blockchain false
1282038ms th_a       db_management.cpp:186         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"index.hpp","line":111,"method":"get","hostname":"","thread_name":"th_a","timestamp":"2017-06-03T01:21:22"},"format":"maybe_found != nullptr: Unable to find Object","data":{"id":"2.1.0"}}]}
1282038ms th_a       object_database.cpp:74        flush                ] object_database flush object_database...
1282048ms th_a       fork_database.cpp:35          reset                ] fork database reset
1282048ms th_a       object_database.cpp:88        wipe                 ] Wiping object database, /Users/albert/bitshares-core-core/witness_node_data_dir/blockchain/object_database
1282048ms th_a       object_database.cpp:90        wipe                 ] Done wiping object databse.
1282048ms th_a       object_database.cpp:95        open                 ] Opening object database from /Users/albert/bitshares-core-core/witness_node_data_dir/blockchain ...
1282048ms th_a       object_database.cpp:101       open                 ] Done opening object database.
1282055ms th_a       db_debug.cpp:85               debug_dump           ] total_balances[asset_id_type()].value: 0 core_asset_data.current_supply.value: 1000000000000000 

...


2929304ms th_a       db_management.cpp:69          reindex              ] replaying block 280
2929304ms th_a       block_database.cpp:200        fetch_by_number      ] e.block_id 00000118d0c538b11cbe98efd1162e1ec3e5147a, result.id 000000016a04e0f7b1e40775aa6cc9b5072e3b85
2929304ms th_a       block_database.cpp:201        fetch_by_number      ] e: {"block_pos":1608287,"block_size":0,"block_id":"00000118d0c538b11cbe98efd1162e1ec3e5147a"} 
2929304ms th_a       block_database.cpp:202        fetch_by_number      ] result: {"previous":"0000000000000000000000000000000000000000","timestamp":"1970-01-01T00:00:00","witness":"1.6.0","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","transactions":[]} 
2929305ms th_a       block_database.cpp:209        fetch_by_number      ] caught fc::exception in fetch_by_num 10 assert_exception: Assert Exception
result.id() == e.block_id: 
    {}
    th_a  block_database.cpp:204 fetch_by_number
2929305ms th_a       db_management.cpp:73          reindex              ] Reindexing terminated due to gap:  Block 280 does not exist!

**Comment by abitmore** [comment]
It's a `null` block, aka default-constructed/uninitialized. It means that block has not been saved to database correctly.
 
The ID of your block 281 is not identical to what we have on the BitShares production network, so I guess you're running a private test network. If you've changed some code, the real reason of your issue may vary. More info may be needed.

**Comment by lanhaoxiang** [comment]
it's now resolved~ thanks
