### ISSUE TITLE
From Poloniex Exchange's Alert

### ISSUE THREAD

**Issue by fundon** [bitshares/bitshares-core#323]
https://poloniex.com/exchange#btc_bts

> BTS is currently under maintenance or experiencing wallet/network issues. Deposits and withdrawals will remain disabled until a solution is found, which may require an update from the BTS team. Any updates must be tested and audited before enabling.

**Comment by oxarbitrage** [comment]
this same message was present last week. as cryptofresh was down, we think it was somehow related as polo could be using the cryptofresh node, api or something.

now cryptofresh is totally up and this msg is there again. we need some contact with polo dev team in order to see whats going on, i know the bitshares community haves contacts with bittrex but not sure about polo.

the issue is not something broken in the bitshares network or core, maybe the node they use is down right now but we don't even know whats node is that. with the memory needed to run a full node they are maybe out of ram, we can provide them alternatives to run a reduced node but it is pure speculation if we can't contact them and get from first hand whats going on.

if anyone have any kind of possibility to start a line of conversation with polo devs to resolve this issue(and future ones) will be great.

**Comment by grctest** [comment]
Perhaps related to the fact that their '[poloniexcoldstorage](http://cryptofresh.com/u/poloniexcoldstorage)' Bitshares account hasn't moved any funds since Sep 4 '16?

**Comment by oxarbitrage** [comment]
i have an open ticket with them to see what we can do to remove the message. submitted yesterday to the dev team of polo, no response yet.

**Comment by oxarbitrage** [comment]
the alert has gone by now since yesterday from poloniex but there was no response to ticket yet to see what was causing it.

**Comment by oxarbitrage** [comment]
ticket has no response from poloniex. whatever is the case, this is not something we can fix from the core code. Closing the issue.
