### ISSUE TITLE
Computation of number of committee members is wrong

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#353]
https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_maint.cpp#L247 was probably c&p'ed from https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_maint.cpp#L162 - should have been modified to use _committee_count_histogram_buffer instead of _witness_count_histogram_buffer .

**Comment by pmconrad** [comment]
Tests indicate that until now this bug has had no effect.

Until around block 20000 the bug results in 500 committee members (which is cut back to the 11 init members). Before the first actual committee member is registered, both the bug and the corrected version either agree about the number of committee members, or the computed numbers are both less than the minimum 11.

We still need to add a hardfork, but it can probably be cut back to fix the default behaviour later.

**Comment by pmconrad** [comment]
WIP: https://github.com/pmconrad/graphene/tree/issue_353

**Comment by liondani** [comment]
just for the records I get that message every 3 sec and I can't run the testnet because of this...

494044ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33441859507574 / 451625188779455
1494044ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1647041ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33441862981443 / 451625190518227
1647041ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1759781ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33441857826371 / 451625194495673
1759781ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5
1919263ms th_a       db_maint.cpp:253              update_active_commit ] Different stake targets: 33441855261230 / 451625197543149
1919263ms th_a       db_maint.cpp:272              update_active_commit ] Committee member count mismatch 3 / 5

**Comment by oxarbitrage** [comment]
closing as issue was resolved in the new release.
