### ISSUE TITLE
Allow First Time Creation of Lifetime Membership on a Premium Account

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-core#354]
Currently to create a premium account the wallet needs to have a lifetime membership first which means a user would need to buy a lifetime membership for a non-premium account before buying it for a premium account. This is unfair.

If a user wants to buy only one lifetime membership for a premium account, the only way to do this is to have another user with a lifetime membership buy it for them then transfer control of account using a paper wallet key generator to attach new private owner keys. This is beyond many users' abilities and can be unsafe if done incorrectly. It also requires the user know someone with a lifetime membership.

I am not sure if this is a UI issue or a core issue but I guessed it should go here. I am sorry if this is a UI issue, I will open it there and reference it to here. It feels like a core issue to me but please correct me if I am wrong.

I suggest a means to allow a user buying a lifetime membership for the first time to be able to pay for the premium account at the same time as the lifetime membership. Currently this is impossible.

**Comment by pmconrad** [comment]
It is neither a UI issue nor a core issue.

The thing is, someone has to pay for creating an account. In return, the creator will receive part of the fees paid by that account. Sites like OpenLedger invest the upfront payment for account creation in the hope that, over time, they make a profit. Obviously, the risk they are taking increases with the price for creating accounts, which is why they usually disallow premium accounts.

But that doesn't mean it's impossible. You only have to find someone who will do it. Someone might even want to make a business out of that. Perhaps ask fav on bitsharestalk, or someone from OpenLedger.

**Comment by landry314** [comment]
I see what you mean. Open Ledger is taking a risk by paying for someone's first account because they might not use it much and generate fewer fees back to them as the referrer than they paid out or they might immediately create a lifetime account and become their own referrer and cut out Open Ledger altogether.

But, don't the fees for the lifetime account also get paid 80% back to Open Ledger? That certainly covers their cost for a non-premium account or a premium account which is much cheaper than a lifetime membership. Or am I mistaken?

Yeah, I guess I should talk to Open Ledger about this. If they allowed premium accounts to be paid for by them if a lifetime membership was also purchased at the same time, it could work. I am not sure the mechanism to make sure the user would immediately make it premium exists. Does this sound technically possible?

**Comment by Ashaman-** [comment]
Someone can also build a 3rd party app that allows registration of premium names. Use code from the bitshares paper wallet webapp to generate keys, and submit the pubkeys along with a payment in cryptocurrency of choice with the desired premium name. When payment is received, the account is registered and has its pubkeys overwritten with the ones submitted by the user.

**Comment by pmconrad** [comment]
> But, don't the fees for the lifetime account also get paid 80% back to Open Ledger? That certainly covers their cost for a non-premium account or a premium account which is much cheaper than a lifetime membership. Or am I mistaken?

Exactly. *If* you upgrade, they will make a profit even with a premium name. But because they don't know if you will do that, they don't allow premium names for normal users. Like Ashaman suggested, you can make a service out of this and even earn some money.

**Comment by landry314** [comment]
Ok, I am going to revisit this one more time...

Couldn't the core be changed so that I can pay for my lifetime membership with the premium account I am about to create? We could have another option which is a package of premium AND lifetime in one account, combine the fees and make it simple.

OR, we could add the ability to transfer lifetime membership from one account to the other. This would also solve the problem, maybe only allow it once if you are worried about it becoming a commodity... or only allow it between accounts created from the lifetime membership itself? Then I could create a premium named account with a lifetime membership account and then immediately transfer the membership to that account. It could also be done in one "package" or command if necessary.

**Comment by pmconrad** [comment]
You cannot pay from the account you are about to create, because a new account has no funds, and it has to exist before you can send funds to it.

Transferring LTM would interfere with the business model of referrers, so I don't think that this will be implemented. However, this is the wrong place for such a discussion - you can discuss such a change on bitsharestalk for example, or submit a formal proposal here: https://github.com/bitshares/bsips/issues

**Comment by platon-projects** [comment]
Sorry, can anyone help me with creation of a premium wallet, like what wallet or website I need to pay for the membership

**Comment by abitmore** [comment]
> Sorry, can anyone help me with creation of a premium wallet, like what wallet or website I need to pay for the membership

https://t.me/btsWalletHelp
