### ISSUE TITLE
why there is one propose_builder_transaction2 there?

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-core#365]
when using cli-wallet, add one operation(named aaa) to builder transaction, if we don't use propose_builder_transaction2 to wraper it, there will be one error info "the committee account cannot directly...." .

but if we use the propose_builder_transaction2, the system will only regard it as a proposal object but not the real operation(aaa). and won't call real operation(aaa)'s do-apply function.

could you pls help show me some way to avoid this propose_builder-transaction2 here? thanks.

**Comment by xeroc** [comment]
The `propose_builder_transaction` call in the cli-wallet doesn't work because it misses to add a "fee-paying-account" to the transaction. That "bug" is fixed with `propose_builder_transaction2`. You will need to use the latter one, or the transaction builder directly

**Comment by cxxcunow** [comment]
but if I write one wallet-api and sign_transaction directly mark the broadcast as true, there will be following error info : committee account cannot directly .... and Missing Active Authority ...

**Comment by abitmore** [comment]
@cxxcunow "committee account cannot directly ..." means you're trying to transact from the "committee-account" directly, which perhaps means you used a wrong account id in your transaction, or forgot to put data into an account id field, since id of "committee-account" is `1.2.0` which is the default `account_id_type()`. Show us the real transaction, we may be able to help.
