### ISSUE TITLE
whether there is a restriction for  object in database?

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-core#366]
for example, if we add one attribute called "vector<block_id>" into account_object, and we will update this object with new generated block_id, but I don;t know whether the database has any restriction with the object size, if there are too many blocks, so the size will be very much.

**Comment by pmconrad** [comment]
Why do you want to do that?

**Comment by abitmore** [comment]
I guess he's working on a plugin, or a forking project.

Anyway, technically it's a memory consumption issue. I don't think there is a data storage issue, since in Steem there are much bigger objects being stored in the object database (as of writing more than 64GB in total), and it's not hard to do some stress tests. However, updating big objects is expensive. For better performance it's better to store this kind of data with a new object/index that has an account_id_type field and a block_id_type field, so there will be many small objects instead of less big objects. Check the different between implementation of witness voting in BitShares and Steem, IMHO the latter is better. Not to mention how bad performance `vector` will be when the size become too big and need to resize.

**Comment by oxarbitrage** [comment]
as @abitmore answer there is no restriction, just a matter of how much ram you need to run a bigger database as it gets fully mapped into memory. closing the issue.
