### ISSUE TITLE
A reputation system for UIA's and MPA's

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-core#371]
Since UIA's and MPA's can be arbitrarily created by anyone in the community, it would be nice to have a reputation system backed by the voting mechanism to help lend credibility to assets. The idea here is that an asset could receive an upvote or a downvote. The weight of the votes would be commensurate with the number of shares owned by each account casting votes. Assets would then have those votes backing it to help people determine whether it's legitimate or not. Optionally, it might be nice for the detail behind these votes containing a written testimonial limited to a reasonably low number of characters, possibly similar to a tweet.

- vote count
- vote weight
- comment

OPEN.BTC [55][450,000,000]

Without a reputation system for assets, it's possible that scammers could fool unwitting users into investing in worthless assets. As it stands today, the only protection against this is being actively involved in the community and various chat rooms.

Ideally, assets would start out with a reputation that is below an acceptable threshold. Thus, community involvement would be necessary in order to lend credibility to the asset and would protect the community.

I can understand how this may be controversial. If the method I have proposed for revealing assets that can be trusted, I'd ask that the community actively discuss other methods to achieve the same end goal.

**Comment by ThomasFreedman** [comment]
In general I believe this is a good idea. Please note however that although users can create their own MPAs, they should have multiple independent feed providers. Currently this is done by witnesses. An MPA without feed sources is inherently untrustworthy. Users could vote on that basis, thus providing input to the MPA's reputation.

I also agree with you that rep scores should start off minimal or even zero and only come up with community input.

**Comment by wmbutler** [comment]
Agreed, it's probably not important for MPAs.

**Comment by abitmore** [comment]
We can make use of the white-listing / black-listing feature. Stake holders, especially top proxies, put the "bad" assets into their black lists, UI then can warn the user based on that info.

**Comment by jbahai** [comment]
Reputation of UIA/MPAs is good. The issue arises where you have whale holders and/or exchanges who use this as a means of suppressing competition on the DEX. Before an entry has an opportunity to be known a whale holder can vote their reputation into negative. Similar effects could be had by proxies who for various reasons could be making 'wrong' decisions on a new UIA potentially based on bad information like false rumours/FUD.

In Peerplays for bookie, we had to tackle the situation of what happens when the blockchain gets bad data regarding a result. In other words what happens when the data the witnesses fed turned out to be wrong in the real world. What we came up with is a community curation method where a review could be instigated and allow for witnesses to republish the results. It is not anticipated that this will be required often, however, it gives the witnesses an opportunity to correct something which clearly millions of eyes will see is wrong prior to some kind of action to follow that will be immutable, ie. payout results from a game. 

I would suggest some similar method should be made available to avoid abuse of such a scoring reputation system as we have had evidences can and will happen as it has in Steem. If there was an opportunity for others to call for a manual review, it would basically allow witnesses to step in and become the adjudicators on the decision. They can cast their votes on a binary decision on whether the vote casting was justified or not. Yes = vote stands, No = vote weight 0.

In real world law, this maybe likened to something called a vexatious litigant. Someone who uses the justice system as a weapon for their own vendetta instead of using it for justice. If they continue this pattern a judge can rule to not allow them to be able to file any more lawsuits. Rather, they would be forced to have to pass a review within the legal system before it will become a real case they can file. Effectively their rights to use the justice system 'rate limited'. In this instance if a vote is found to be unjustified by a peer review of witnesses, the results would be voters weight in that particular UIA/MPA being brought to zero... effectively taking away their say in that particular matter, but not in others. 

That said, I would suggest that the comment field always be required as part of this new process of scoring UIA/MPAs. 

This review method could also be limited if abused. If after 5 reviews being found to be YES results, where the vote result stands, that user reporting capabilities will no longer be accessible or perhaps disabled for  90 coindays. 

I realize some of what I am talking about is going to require some rather advanced coding. I would suggest waiting for the release of bookie to look at how we have done it to help speed up the process. 

The scoring as proposed by OP if it can be implemented sooner maybe a good starting point at least for an early version for people to try and get incorporated in community culture.

**Comment by TheTaconator** [comment]
@ThomasFreedman brings up a good point about the number of feed sources for MPAs.  The HERO asset, for example, has whitelisted feed sources who need not be witnesses.

**Comment by pmconrad** [comment]
IMO this is a dangerous road to take. It allows abuse, and it implies responsibility on the side of the shareholders.
I'd prefer if the DEX remains neutral wrt the assets traded on it.

**Comment by wmbutler** [comment]
I agree that there are negatives. Really wish there was a better system for managing reputation.

**Comment by abitmore** [comment]
I don't think it should be done in core. Closing.
