### ISSUE TITLE
get_ticker for BTC/USD return incorrect price?

### ISSUE THREAD

**Issue by ulion** [bitshares/bitshares-core#388]
curl --silent --data '{"jsonrpc": "2.0", "id":1, "method":"get_order_book", "params":["USD","BTC",5]}' https://bts.transwiser.com/ws

the result orderbook and the ticker too are all not match with what in the UI.

so what's going on here?

**Comment by oxarbitrage** [comment]
i am not sure if i understand fully, but here some info that may help:

- use a limit of 50 instead of 5 to see all the asks, the pair haves now 40 asks so use:

`curl --silent --data '{"jsonrpc": "2.0", "id":1, "method":"get_order_book", "params":["USD","BTC",50]}' https://bts.transwiser.com/ws | jq`

- ticker is pulled by another call:

`
curl --silent --data '{"jsonrpc": "2.0", "id":1, "method":"get_ticker", "params":["USD","BTC"]}' https://bts.transwiser.com/ws | jq
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "base": "USD",
    "quote": "BTC",
    "latest": "5143.24168429148267023",
    "lowest_ask": "5000.00000000000000000",
    "highest_bid": "4111.67512690355306404",
    "percent_change": "6.66641100535372289",
    "base_volume": "595.66579999999976280",
    "quote_volume": "0.12486238000000001"
  }
}
`  

volume information also:

`
root@alfredo:~# curl --silent --data '{"jsonrpc": "2.0", "id":1, "method":"get_24_volume", "params":["USD","BTC"]}' https://bts.transwiser.com/ws | jq
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "base": "USD",
    "quote": "BTC",
    "base_volume": "595.66579999999976280",
    "quote_volume": "0.12486238000000001"
  }
}
root@alfredo:~# 
` 

- in the UI some rounding and number formatting is done but data is all the same, reference urls:

http://bitshares-explorer.io/#/markets/USD/BTC
https://bitshares.openledger.info/market/USD_BTC

**Comment by ulion** [comment]
@oxarbitrage That is exactly the problem:

> "lowest_ask": "5000.00000000000000000",
> "highest_bid": "4111.67512690355306404",

indeed there are many asks and bids between 4111 and 5000 in the UI, please correct me if I am wrong.

**Comment by ulion** [comment]
well, I think I was watching OPEN.BTC, so what's the difference between OPEN.BTC and BTC in bitshares?

**Comment by oxarbitrage** [comment]
BTC is a smartcoin created by the network while OPEN.BTC is an user issued asset created by openledger.

**Comment by oxarbitrage** [comment]
some info on smartcoins:
https://bitshares.org/technology/price-stable-cryptocurrencies/
user issued assets:
https://bitshares.org/technology/user-issued-assets/
