### ISSUE TITLE
Implement Bitshares as EOS contract or an EOS clone

### ISSUE THREAD

**Issue by bitcoiners** [bitshares/bitshares-core#418]
Any plans to adopt EOS as Bitshares blockchain? 
EOS pre-release is ready for early development. This might be a good time to start implementing Bitshares as an EOS contract.

**Comment by xeroc** [comment]
> Bitshares as an EOS contract.

I had plenty of discussion about this with Daniel Larimer and we believe that it makes no sense business-wise to implement BitShares on top of EOS. BitShares is a (potentially profitable) DAC (company) while EOS rather compares with a sociaty. The economical models behind those two is so different that I personally prefer BitShares to stay on its own Blockchain.

For instance, a BTS token on EOS would have no value, because it cannot vote for producers and does not earn any fees (even if the smart contracts have a fee associated, that fee part of the code can be removed and the fee-less contract can be deployed as alternative).

What can make sense is to leverage the lessons-learned from EOS and integrate parts of their code into BitShares - for instance their RPC interface seem to be quite nice.

**Comment by bitcoiners** [comment]
Well, I suggest this is discussed further in a wider forum, as many are expecting Bitshares to adopt EOS, and clarity on plans would be appreciated by all. 
Secondly, If Bitshares is to stay a separate blockchain, a few things need to be considered. 
1. Need to adopt best features of EOS (and Steem) in Bitshares blockchain. 
- I would suggest considering dropping transfer and maybe even trade fees in favor of metered model of Steem and EOS. This is would increase adoption and improve ease of use.  
2. Need to consider that if Bitshares does not move to EOS, another DEX contract will be implemented by somebody and that DEX will be in competition with Bitshares.
3. EOS will be very scalable  and run with low latency (sub-second), which will be a significant advantage long term over Bitshares, unless it adopts same tech. 
4. Lack of smart contract support in Bitshares is significant disadvantage vs EOS. 
5. In event of Bitshares staying separate it will need to inter-operate with EOS as well as possible and this too needs to be planned.

**Comment by bitcoiners** [comment]
Alternatively Bitshares can be implemented as an EOS clone. This way new EOS based Bitshares tokens will be base tokens of the blockchain with all the vesting privileges.

**Comment by bitcoiners** [comment]
If Bitshares is to survive long term it will have to adopt best blockchain tech available. At this time EOS is the most advanced blockchain tech and Bitshares has to evolve to stay relevant.

**Comment by pmconrad** [comment]
At this time EOS is mostly hype, and not a blockchain at all.
I agree that this should be discussed in a wider forum, a github ticket is definitely not the right place.

**Comment by bitcoiners** [comment]
Created a steem post to discuss this further.
https://steemit.com/bitshares/@slavix/should-bitshares-adopt-eos-blockchain

**Comment by pmconrad** [comment]
Good. Closing here.
