### ISSUE TITLE
Implement an easier way to transfer real currencies from your bank account to BitShares

### ISSUE THREAD

**Issue by arnauze** [bitshares/bitshares-core#423]
Hello everybody, 

Everything is in the title. I am a new user of BitShares, and really interested and impressed by this concept, and I just think that the adoption would be even bigger if we had a way to transfer real currencies from our bank accounts around the world to BitShares without having to buy cryptocurrencies on another website.

Also, a sort of social network allowing traders to share their experiences and thoughts withing BitShares would be incredible. A little bit like eToro. 

Have a very nice day

**Comment by pmconrad** [comment]
You can do that, but you'll have to get your account verified with OpenLedger/CCEDK. In the GUI, click on the "Depoit/Withdraw" tab, then switch from "Gateway" to "Fiat". You can deposit/withdraw USD or EUR for OPEN.USD and OPEN.EUR.

We have a public forum at https://bitsharestalk.org, and https://steemit.com is a blockchain-based community where you'll also find BitShares enthusiasts.

Closing here, because it's not a backend issue.
