### ISSUE TITLE
Add basic trader features

### ISSUE THREAD

**Issue by cryptocreeping** [bitshares/bitshares-core#456]
Trailing stop losses, stop losses, limit sell orders, conditional limit orders (buy and sell)

**Comment by cryptocreeping** [comment]
These features should attract actual traders to the dex.
I use these features daily in my day job as a day trader at an investment bank.
These functionalities allow traders to make calculated risk decisions instead of decisions based on random luck.

**Comment by pmconrad** [comment]
Good suggestion, wrong place. Please create a BSIP at https://github.com/bitshares/bsips .

**Comment by oxarbitrage** [comment]
this will be something great to have but there are a lot of possible problems to discuss, we can't just implement. on the most basic form everything reduces to maintain a list of stop loss(and other kind of orders) and execute when this levels are reached by market price. this is something that can be done fully client side. the orders can fail because of low liquidity between other factors, there are several things to consider.

a core plugin could be made to maintain the list and expose api calls to create the orders however i am unsure if the core can execute orders in the name of the user or even if this will be a good practice. another option will be to fully support the new order types by creating new operations, more alternatives can be easily found but the devil is in the details.

i propose to move the discussion to the forum or other channels and then as @pmconrad said formalize it in a BSIP. we need to write down all the options, all the possible problems, all the technical details on how it will be done and propose it to shareholders.

**Comment by cryptocreeping** [comment]
So is this being reopened else where in the right github repository? Don't
want this key functionality request to get lost in the abyss of a forum or
chat.

**Comment by abitmore** [comment]
@cryptocreeping please check https://github.com/bitshares/bsips . Need to create an issue there.

**Comment by cryptocreeping** [comment]
I created it and it was closed. No way to migrate it or copy/paste it?

**Comment by abitmore** [comment]
@cryptocreeping I didn't find it, link please? In the BSIP repository, features need to be described in detail, need to write the "why/what/how", but not just "I want", so copy/paste is not enough.
