### ISSUE TITLE
Add Ability to Include an Icon for Each Asset on Blockchain and Through a Gateway

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-core#462]
Many exchanges include icons next to each asset to make them easier to see by eye and to make things prettier. The BitShares DEX GUI should be made to do this too but who would decide which icon goes with which asset and how would we make sure each asset had an icon?

The best way to implement this would be to add an icon data space to the asset variables where users manage their UIAs. Also, somehow allow gateways to set icons for all their coins. Then the GUI can just display them where it needs to.

This would require a change in the core code to add this feature to all assets, wouldn't it?

Here is what the asset list looks like on Binance:
![binance asset list](https://user-images.githubusercontent.com/6866501/32414125-11dec38a-c1ee-11e7-835e-3d6ab37c8642.jpg)

**Comment by oxarbitrage** [comment]
this is interesting, when i made the explorer assets page i had to use the icons that were available in the bitshares-ui at https://github.com/bitshares/bitshares-ui/tree/staging/app/assets/asset-symbols . this is totally off chain and need to be maintained manually on every place this images are located. 

a while later we were discussing in telegram the possibility to upload avatars to user account. a company or individuals will definitely prefer their logo instead of the default ones and the same goes with the assets.

storing the image in the blockchain will have space problems so an url seems to be more reasonable, later @billbutler mentioned that we could use just an email address with gravatar(we were discussing user image here). whatever is the case the way to go should be with an email or url. This can bring other problems like who upload what, copyright, offending/porn images, etc but let's discuss just the technicals here.

Both objects, the account and the asset haves an extension field, you can check it out at:
http://23.94.69.140:5000/full_account?account_id=1.2.12376
and
http://23.94.69.140:5000/get_asset?asset_id=1.3.0

I suppose this are for extra stuff, in the chat when i mentioned the possibility to add url of logos there @xeroc mentioned some possible problems that i can't remember now. i didn't had the time yet to really check if this it will be possible or if extension fields are for something else but it will simplify things a lot if we can just use a field already there.

**Comment by abitmore** [comment]
It's not a consensus change, so IMHO no need to change backend, instead, the GUI can add one more filed into the json of `"description"` field:
```
    "description": "{\"main\":\"OBITS is a digital token, the official token of the DC, blockchain powered via the platform OpenLedger and people driven on the base of the OBITS Bloggers’ Club 500.\\n\\nIt is a new type of sharing economy where it is possible to earn a share of the fees generated by the platform OpenLedger. \\n\\nOBITS represents a large share of the digital token revenue generated by not just current but also future initiatives added by https://www.openledger.info over the next few years..\\n\\nCheck out more on http://obits.io with english speaking support or chinese website for OBITS is: http://obits.hk with chinese speaking support.\\n\\nAlso check out the OBITS video, OBITS - Powered by the people:  https://youtu.be/DC86cV4vXIU\\n\\n\\n\",\"short_name\":\"OBITS\",\"market\":\"\"}",
```

**Comment by abitmore** [comment]
Please repost this to https://github.com/bitshares/bitshares-ui

**Comment by landry314** [comment]
Ok, I will do this...

It appears to be three issues:

1) Extend UIA description to include a link to the github page where its icon can be added and make the GUI be able to link there.

2) Include Avatars in a user's profile somewhere? I don't think this is a new issue.

3) Add icons to the Portfolio by fetching them from the github page where they are stored.

I will try to sort this out and post it all later tonight.
