### ISSUE TITLE
missing  initial value. withdraw_permission_create_evaluator: claimed_this_period of withdraw_permission_object

### ISSUE THREAD

**Issue by btsabc** [bitshares/bitshares-core#502]
It seems should
withdraw_permission_create_evaluator: claimed_this_period of withdraw_permission_object initial value=0.
Chaos only happen in a particular situations and time.

no initial 0, maybe no problem with g++ compiler, but problem in vc and clang with optimized compile.

```
        p.withdrawal_period_sec = op.withdrawal_period_sec;
        p.expiration = op.period_start_time + op.periods_until_expiration * op.withdrawal_period_sec;		        
        p.period_start_time = op.period_start_time;
+       p.claimed_this_period = 0;
     }).id;
  } FC_CAPTURE_AND_RETHROW( (op) ) }
```

**Comment by btsabc** [comment]
And not initial  0 at the beginning of any period also is a little issues ,it cause the multi claims of withdraw in a  period to  be invalid except first  period.

**Comment by abitmore** [comment]
According to the [code](https://github.com/bitshares/bitshares-core/blob/2.0.171105a/libraries/chain/include/graphene/chain/withdraw_permission_object.hpp#L66), data type of `claimed_this_period` is `share_type` aka `fc::safe<int64_t>`, so it should already have an initial value of `0` (see [the definition of fc::safe](
https://github.com/bitshares/bitshares-fc/blob/2593760687e89c8878f0e537ae9b9963fa46b210/include/fc/safe.hpp#L23)):
```
   template<typename T>
   struct safe
   {
      T value = 0;
```

Your issue may be caused by something else, can you describe it clearer?

**Comment by btsabc** [comment]
@abitmore  You're right. safe type always initialized to 0. 
I close this issue.

**Comment by btsabc** [comment]
@abitmore  You're right. safe type always initialized to 0. 
I close this issue.

**Comment by btsabc** [comment]
@abitmore  You're right. safe type always initialized to 0. 
close this issue.

**Comment by btsabc** [comment]
@abitmore  You're right. safe type always initialized to 0. 
close this issue.

**Comment by btsabc** [comment]
@abitmore  You're right. safe type always initialized to 0. 
close this issue.

**Comment by btsabc** [comment]
@abitmore  You're right. safe type always initialized to 0. 
close this issue.
