### ISSUE TITLE
Add API to query for  recent order  histories of one account in one market

### ISSUE THREAD

**Issue by btsabc** [bitshares/bitshares-core#503]
Getting  recent order  histories of one account in one market is not easy by current data index
，because it maybe  It happened a long time ago。

**Comment by abitmore** [comment]
Please check the `elasticsearch` plugin in `develop` branch and a WIP document [here](https://github.com/oxarbitrage/worker-proposals/blob/master/elasticsearch-plugin.md), and comments [here](https://github.com/bitshares/bitshares-core/issues/358#issuecomment-344710980) are related.

Due to this, we are not going to add more API's for querying special histories from the object database. Closing this issue.
