### ISSUE TITLE
question of design

### ISSUE THREAD

**Issue by lonnieOST** [bitshares/bitshares-core#514]
Greetings,

I have come across the bitshares exchange and github site and like the peer-to-peer design for the exchange.

I am trying to get a feel for how things are laid out. From what I can see, the bitshares-core runs on the peer nodes and establishes links with other bitshares nodes as the backend exchange which it seems that the bitshares-ui provides a frontend cloud interface that uses API calls to the backend nodes.

Also, I see that there are executables for different platforms as well as the web ui interface and also assume that these executable manage the local wallet and make API calls to the bitshares-core backend nodes.

Is this correct?

If it is, the do I assume that the bitshares-core can be run on a few LAN nodes while the bitshares-ui can be set up on a web server and the bitshares executables can be run locally as well?

Any clarification on the design would be greatly appreciated.

Thanks,
Lonnie

**Comment by oxarbitrage** [comment]
Hi Lonnie, welcome to bitshares :) that's pretty much correct. Let me try to explain a bit more with my limited skills, i may not be the best person to explain this ... someone pls correct me if needed. 

There is a fixed number of block producers in the network connected by p2p. This machines running `bitshares-core` validate blocks(sign when they are valid) that are produced every 3 seconds in current live network. This consensus is done by DPOS(https://steemit.com/dpos/@dantheman/dpos-consensus-algorithm-this-missing-white-paper).

So when an operation like a transfer to send asset from A to B is created from the GUI what is is happening is that the operation is build and sent by the GUI to an API node in a format that the node can understand. An API node is also `bitshares-core` but does not need to be a producer, it just share the same blockchain data and expose the data to the public while it can also receive and broadcast operations. An API node will forward the new operation to a producer that will sign and broadcast back to the network marking the block as valid. After consensus asset will be transferred from A to B, this is very fast compared to other consensus algos used by other blockchains. The new version of the blockchain where user B now have more asset and user A less asset will be broadcast to the entire network and all participants will be upgraded to this new longer chain.

API nodes are also connected by p2p to the network so their own version of the blockchain is updated when a new validated block arraives.

Nodes(api nodes, block producer or any other type of participant) are always in sync(have the same blockchain data) except for a small period of time that a new block is arriving the network and being validated.

In regards to the LAN and such, yes, it is possible to have your own blockchain that does not at all interact with the bitshares network, you can get started with that with this: https://github.com/bitshares/bitshares-core/wiki/private-testnet

There is also a public testnet where you can test all kind of things with virtual money(https://testnet.bitshares.eu/) and many other stuff in bitshares related mainly to trading, asset creation, governance, etc that you will be able to learn if you have an open mind and also have the time, because it is not easy stuff.

Hope it helps.

**Comment by lonnieOST** [comment]
Thanks for your reply and for explaining more about Bitshares as it is very
helpful.

I did also find a general Bitshares users forum, but not really any
developers mailing list or forum which is probably better suited for these
types of questions than issues on the github base.

Do you know of any mailing lists or forum that I might join for other
related questions as I wrap my head around how the code functions better?

Thanks again,
Lonnie

**Comment by abitmore** [comment]
There was a technical/develop board in the forum, later merged into technical support board after BM left due to lack of activities. There are some mailing list at http://lists.bitshares.foundation/listinfo, but currently no much discussion there as well. In the meanwhile you can join https://t.me/BitSharesDEX and perhaps ask someone to invite you to the dev group/channel. I'd admit that mailing lists are better for archive.

**Comment by oxarbitrage** [comment]
yes, the telegram developers group for bitshares should be the best place. look for my username(oxarbitrage) in the bitshares dex channel, send me a pm with yours and i'll send you an invite. there is a discord channel as well for bitshares devs but the telegram currently haves the most skilled people. i am closing the issue now but feel free to reopen if needed.

**Comment by lonnieOST** [comment]
Hello,

I am currently trying to get set up on Telegram, but go delayed. Why do
that ask for your telephone number for an online chat system?

Also, had one other question.

As I am starting my journey to dig into the Bitshares code, I started
looking on the github and see the "core" for the actual BTS API nodes as
well as see the "bitshares-ui" that you can place on a web server to call
the "core" API for data.

I have a Ubuntu 16.04 system and Windows system that are able to run
binaries but do not see how the binaries are built.  Actually, it seems
that the bitshares-ui "might" be used to put on a web server as well as to
build binaries, but I am not clear on this. Could you please explain this
part of the process to me?

Thanks,
Lonnie

**Comment by abitmore** [comment]
@lonnieOST please check https://github.com/bitshares/bitshares-core/blob/develop/README.md for the core, https://github.com/bitshares/bitshares-ui/blob/staging/README.md for UI.

**Comment by lonnieOST** [comment]
Thanks for the links.

Actually, I had briefly run across them already but did not heavily read
into the "Installable wallets" (
https://github.com/bitshares/bitshares-ui/blob/staging/README.md) which is
what I was seeking. I sometimes like to read through code to get a fell for
how things come together in a project.

Thanks again,
Lonnie
