### ISSUE TITLE
Peg Lifetime member fee to static BitUSD value

### ISSUE THREAD

**Issue by timelf123** [bitshares/bitshares-core#555]
Because BTS prices have gone up so much this month, many people want VIP price to be pegged to USD. This ticket is being submitted to recruit devs and someone to create a WP to make this happen.

**Comment by oxarbitrage** [comment]
hi there, this will need to be detailed on how it will be done technically in a BSIP: https://github.com/bitshares/bsips
there is an interest on also supporting worker proposals in bitusd instead of bts that may be included in the same bsip. 
will require planning, discussion and time, easier and faster is that the committee lower the fee for a LTM.

**Comment by grctest** [comment]
I fully agree that we should peg fees to bitUSD (or any other suitable mainstream bitasset like bitcny, etc), so that fees remain static and don't negatively impact the network when the BTS price fluctuates.

**Comment by oxarbitrage** [comment]
proposal to reduce network operation fees including `account_upgarde` used for upgrade an account to LFT is being voted by the committee at this moment.
https://bitsharestalk.org/index.php/topic,25698

**Comment by pmconrad** [comment]
Closing since this is (was) being discussed in a broader scope in https://github.com/bitshares/bsips/issues/48 .
