### ISSUE TITLE
Virtual operations should be excluded from transactions

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#588]
fill_order_operation contains this piece of code that prevents it from ending up in a transaction: https://github.com/bitshares/bitshares-core/blob/015026f005123a507c572a0318565383c92e0820/libraries/chain/include/graphene/chain/protocol/market.hpp#L156

Other virtual operations should be protected in the same way. Specifically, asset_settle_cancel_operation does not include this validation.

**Comment by abitmore** [comment]
See PR #591.

**Comment by abitmore** [comment]
Update: removed code related to this issue from #591 since this requires a hard fork.

**Comment by cifer-lee** [comment]
so, this could just be resolved by making such change on each leaving virtual operations :P

```
-         FC_ASSERT( amount.amount > 0, "Must settle at least 1 unit" );
+         FC_ASSERT( !"virtual operation" );
```

**Comment by abitmore** [comment]
@cifer-lee this is a hard fork change, need to do it in the "hard fork" way.

**Comment by abitmore** [comment]
Specifically, if you put this operation directly in a transaction, the transaction will be refused by witness node, so it won't be included in blocks.

However, if you put this operation in a proposal, current nodes will accept it, when the proposal get approved or expired, the node will try to execute the operation, due to no evaluator class registered, the execution will fail and the proposal object will be removed.

If simply change the code like above, nodes running new node will reject the proposal in the first place, which means the new code is not compatible with the old code, which means a block containing that proposal (produced by a node running old code) will be reject by the nodes running new code, aka forking.

To get around this, we need to make sure all nodes have upgraded before the code is in effect. So we need to add "hard fork guard" code to only apply the new rule after the specified hard fork (e.g. a pre-defined time point has passed). You can check https://github.com/bitshares/bitshares-core/pull/599/files to see how to add hard fork guard code.

**Comment by cifer-lee** [comment]
@abitmore Thanks, seems I need to add a new hardfork time point `libraries/chain/hardfork.d/588.hf`, but could you tell what the hardfork time should I use?

**Comment by pmconrad** [comment]
Simply use a hardfork time in the far future for now. It will be changed when we're preparing the actual release.

**Comment by abitmore** [comment]
@cifer-lee please use `CORE_588.hf` as file name, and you can pick the time `1600000000` used in https://github.com/bitshares/bitshares-core/pull/599. Sample code is [here](https://github.com/bitshares/bitshares-core/blob/e2be061fcd247deb298fdea4a7221d8c69d11c07/libraries/chain/hardfork.d/CORE_199.hf). And another thing, please develop on top of `hardfork` branch but not `develop` branch since it's a consensus-changing feature. See [Git Flow](https://github.com/bitshares/bitshares-core/wiki/Git-Flow) in the Wiki for more info.

**Comment by cifer-lee** [comment]
@pmconrad @abitmore Thanks I have made the changes under your help. Pls review it~
Sorry to say that I have not tested locally, since I wonder if we have a common/auto-integrate test system?

**Comment by pmconrad** [comment]
We have a suite of unit tests that you can (and should) run locally:
```
make chain_test
./tests/chain_test
```

The next step is to ensure that your changes do not collide with the existing blockchain. For this, build the witness_node and run it with --replay-blockchain (in the data_directory of an (almost) fully synched node of course).

Third, the change will at some point be merged into our testnet. A hardfork change will come into effect there, before it is integrated into the main chain. You can test the post-hardfork changes on testnet.

**Comment by cifer-lee** [comment]
@pmconrad Got it~ thank you, I will do my test locally

**Comment by abitmore** [comment]
Done with #698, merged into hardfork branch.
