### ISSUE TITLE
Suggestion: Return transaction_ids when call get_block API

### ISSUE THREAD

**Issue by oflyhigh** [bitshares/bitshares-core#601]
#### STEEM

As we know, the `get_block` API of ***STEEM blockchain*** return an additional section `transaction_ids` which contains the list of txid of `transactions`.

for example, the `transaction_ids` of block 10000000 of STEEM
```
            'transaction_ids': ['e114ced368416efaf25c6c5f8a54c1c68256667d',
                                'd6a01f8af1e4250acc8a76a543c6ed1c2a9e3f0a',
                                '9f48f63edfd40e72ac6c9635dcdcad9d742e5d1c',
                                '77500b74c3a360fa6296c259382f85d0893fdfc9',
                                '2d9a0234054acc45a41b7b96c26faa4063a66307'],
```
If we know `block_num` and `txid`, we can easily extract transaction from block.

#### BitShares

But the `get_block` API of ***bitshares blockchain*** doesn't contain `transaction_ids` in block. If we only know `block_num` and `txid`, we need to do a lot of additional calculations to extract transaction from block. 

#### Suggestion
It should be better if we add a new section `transaction_ids` of block information which return by  `get_block` API.

Thank you.

**Comment by pmconrad** [comment]
This eat up lots of RAM, which is why steem has a compile-time option to disable that index: https://github.com/steemit/steem/blob/develop/CMakeLists.txt#L98

Might be worth adding to ES though.

**Comment by abitmore** [comment]
Currently the `get_block` *wallet_api* returns `transaction_ids` as well as `block_id` and `signing_key`, but *database_api* does not. Those fields are calculated on the fly, so no more RAM is needed, we can argue that it requires more computing resources. The former is a bit more convenient for client apps, however `cli_wallet` itself **is** a client software. Considering that load on API nodes are a bit heavy, it does make sense to move some load to client side. Due to this, I tend to not implement the feature on server side, although it does need some efforts for client software to implement it.

**Comment by oflyhigh** [comment]
OK, got it, thank you for your reply.

**Comment by oxarbitrage** [comment]
a node with elasticsearch plugin activated can already relate transaction id with blocks and operations. it was one of the several issues that elasticsearch plugin resolved.

for install and get started with elasticsearch node:
https://github.com/bitshares/bitshares-core/wiki/ElasticSearch-Plugin

**Comment by abitmore** [comment]
Won't do it.
