### ISSUE TITLE
Allow numbers in asset symbols

### ISSUE THREAD

**Issue by mutagenfork** [bitshares/bitshares-core#620]
Right now, numbers aren't allowed in asset symbols.  It would be handy if it were possible to use numbers, so that symbols like "SP500" were possible.

**Comment by oxarbitrage** [comment]
by the code it seems the numbers are possible but not at the start or end of the asset symbol:

https://github.com/bitshares/bitshares-core/blob/1d0b85998f33c52e1b5073d6de73999f3a29db67/libraries/chain/protocol/asset_ops.cpp#L45-L49

not totally sure but i think you have a good point and at least we should allow the last character to use `isalnum`

**Comment by oxarbitrage** [comment]
i am taking this one as it is the easier HF available and i want to get more familiar with the process to make a few more for the next consensus.

**Comment by oxarbitrage** [comment]
question here. `asset_ops.cpp` does not haves access to database so compare the hardfork date against `head_block_time` is not possible. i saw in other files of the protocol directory that what they did is use `fc::time_point::now()` to compare. this is ok but it will make test cases not possible. other option is to add database support to the file. any advice on how to proceed is appreciated.

**Comment by abitmore** [comment]
`fc::time_point::now()` is a no-go, since it may break consensus. To make the change, need to loose the validation code in asset_ops.cpp, add a hard fork guard code with original rule to asset_evaluator to make sure no rule change before the hard fork, add corresponding hard fork guard code in proposal_evaluator. After hard fork, those hard fork guard code can be safely removed.

By the way this hard fork may need a BSIP and need to be approved by stake holders. It will enable more asset names, thus related to economy.

**Comment by oxarbitrage** [comment]
i see, thanks for the response. it is more complicated than i expected even if the explicatio  on how to do it

**Comment by abitmore** [comment]
Done with #705, merged into hardfork branch.
