### ISSUE TITLE
Implement and test virtual operations

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#67]
_From @theoreticalbts on August 19, 2015 17:9_

Some big fat TODO's in `db_market.cpp` here:  https://github.com/cryptonomex/graphene/blob/eeeab17477a635fcff7f2d294dff8ecf25449b10/libraries/chain/db_market.cpp#L89-L116

This is basically to generate a virtual cancel op to inform account history listeners that orders have been cancelled due to certain asset management actions.

_Copied from original issue: cryptonomex/graphene#250_

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on August 19, 2015 21:5_

Virtual ops generated by a proposed transaction require special attention.

**Comment by oxarbitrage** [comment]
This issue is too old and  already done in current bitshares.

Compare: https://github.com/cryptonomex/graphene/blob/eeeab17477a635fcff7f2d294dff8ecf25449b10/libraries/chain/db_market.cpp#L89-L116

With:

https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_market.cpp#L96-L133

Closing the issue.
