### ISSUE TITLE
witness_node hangs silently when attempting to listen on already-used port

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#77]
_From @theoreticalbts on August 31, 2015 18:38_

Discovered the hard way that it was hanging in `reset_p2p_node()` when I accidentally re-used an occupied server-side port.  This seems like a common error so let's tell the user and exit cleanly instead of simply hanging with no error message.

_Copied from original issue: cryptonomex/graphene#280_

**Comment by vikramrajkumar** [comment]
_From @bytemaster on September 1, 2015 13:20_

I think this is a logging issue.  The P2P code will print a message to warn the user that it is waiting for the port to become available.    It is using the "ulog"

**Comment by oxarbitrage** [comment]
Trying this as is an old issue but still valid as the problem is still there.

@theoreticalbts is right in the fact that there is no error msg , the witness just seems to hang in there.  

But as @bytemaster comments there is an ulog with the error as the node keeps trying connecting when the port is busy. Node will keep doing it forever until ctrl-c but the  nodemaster will not know whats going on.

All the p2p logging is saved to a file in the default config. This is because when a node first start, the configuration is built from this defaults:

https://github.com/bitshares/bitshares-core/blob/master/programs/witness_node/main.cpp#L214-L226

With that configuration we are redirecting all the p2p logging into files. This is correct to me as the p2p logging can be too much for being displayed in witness output console.

With this one can think that the error of the used port should be in the log files. Wrong, as we are using ulog in this particular error the same is not logged to the log files but redirected to a user(not sure how is the configuration of that).

So a witness master that is trying to run a node in an already used port for p2p(note that in the case of rpc port already in use the witness will exit with an exception) will not receive any message in the console and will also not find any print in the log files. So the nodemaster is actually blind until he realize the problem is that. 

I have a solution for this, it may not be the most elegant but will solve the problem. 

https://github.com/bitshares/bitshares-core/pull/264

What the pull request do is first change the ulog to wlog. With that change alone the user will have the error printed in the p2p log files.
Additionally, i used the standard cout to print an additional message in red to the console only for this error so we don't need to mess around with is already done but we can still get the additional info we need to easily solve this problem.

This will result in the following instead of previous behavior that don't show anything.

![issue77](https://cloud.githubusercontent.com/assets/21685097/25256450/27f27910-2607-11e7-945b-4af9d2442b2c.png)
