### ISSUE TITLE
TX and register

### ISSUE THREAD

**Issue by KolosDan** [bitshares/bitshares-core#818]
Hello
Imagine, I have a custom BTS wallet in telegram bot. What I need to is registering new accounts and creating transactions for them via websockets or RPC.

Registering: Can I somehow pull it off without cli_wallet, just pure websocket requests - just having my account keys and user information on preferable username
Transactions: Can I create transactions again without using cli_wallet just pure websocket requests: having sending user's keys and all data needed for tx: to, amount, message and so on.
Thanks in advance, just really tired of exploring tons of docs and libraries. Lurking through docs is cool, but the task is urgent

**Comment by xeroc** [comment]
Since we are talking about a blockchain that requires signed transactions, anything that can create signed transacitons is capable of sending websocket requests to get an account registered.

In you case, you probably need to deploy your own middle-ware that consumes REST/websocket requests and "signs" them to put them into the blockchain.

I recommend you look into bitsharesjs or python-bitshares library.

If you need to "get this done", you may want to look for a dev to hire

**Comment by KolosDan** [comment]
Thank you kindly for the recommendation. I will try this libs.
