### ISSUE TITLE
Add CLI command to add signatures to a partially signed transaction

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#867]
Having a way to add signatures to a partially signed transaction, is useful for off-chain multi-signing and cold storage.

As mentioned in #865, current `sign_transaction` command will clear all existing signatures before adding new ones, but we don't want to change the behavior, so it's better to add a new one.

Note: if modified expiration and / or TaPoS fileds, the old signatures will become invalid, so can't change them as well.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [x] Define Test Cases
- [x] Design / Develop Solution
  - [x] Assigned: @cifer-lee 
  - [x] Estimated: 15 hours (10 AUG: revision required based on refactoring effort, see #1032)
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cifer-lee** [comment]
Claiming this Issue. Will begin work now. Coordinating with @ryanrfox for updates.

**Comment by cifer-lee** [comment]
Need more discussing with this issue. How the multi-sig procedures be implemented and how these to-be-added cli command(s) will be used.

Follow's my thoughts about multi-sig solution:

1. Create a initial transaction, with TaPoS and expiration field assigned. This can be performed on either online or offline machine. When on a offline machine, TaPoS field can be specified manually.
2. Export the initial transaction and import it to offline machine (cold wallet)
3. The initial transaction may or may not taken signatures, up to whether or not signed it in step 1. Anyway, we can sign this transaction using the offline-stored key directly. (Not query required authorities/signatures through api since the offline machine not synced)
4. Export the signed transaction from offline machine and repeat step 3
5. Import the final transaction into a online machine and broadcast it

Willing to hear from other devs..

**Comment by cogutvalera** [comment]
does anybody work on this issue or can I claim it in order to finish ?

**Comment by cogutvalera** [comment]
I want to claim this issue, is it possible ? Thanks !

**Comment by cogutvalera** [comment]
the work is still in progress on this issue or not ?

**Comment by abitmore** [comment]
@cogutvalera this issue has been claimed by @cifer-lee, work in progress.

**Comment by cogutvalera** [comment]
ok sure ! Thank you very much for the info ! Because I couldn't understand if work is in progress or not.

**Comment by abitmore** [comment]
The work in progress pull request is #1032.

**Comment by cogutvalera** [comment]
Yes, understood ! Thanks ! Sorry for misunderstanding, just time confused me and I thought this issue was stopped/paused in development.

**Comment by ryanRfox** [comment]
Removing from 201902, adding to (next) Feature Release.

**Comment by abitmore** [comment]
Fixed by #1032.
