### ISSUE TITLE
Update Git Flow about releasing

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#894]
This issue is about https://github.com/bitshares/bitshares-core/wiki/Git-Flow.

Generally, a consensus changing (hard fork) release need to be tested for a long period before merging to `master` branch. For potential emergency fix on mainnet, which need to be done based on `release` branch which is identical to `master` branch, it's not ideal to update the old `release` branch while testing new release. That said, we need a `testnet-release` branch.

Another thing is about changes needed for testnet, E.G. hard fork time and other logic changes due to destructive testing done in testnet. Apparently, these changes shouldn't be in `hardfork` or `develop` branch, so need to be done in `testnet-release` branch. However, due to this, for final release, we can't merge from `testnet-release` branch. So we need a branch that need to be "frozen" when started testing. I don't know what's the best branch name for it, for now, just name it `pre-release` branch.

So the git flow for consensus changing release should be:

```
[ normal dev branches ] -> [develop]
                               V
                               V
[hardfork dev branches] -> [hardfork] ---> [pre-release] -> [testnet-release] -> [testnet]
                                                V
                                                V
                                            [release]
                                                V
                                                V
                                             [master]
```

Git flow for non-consensus changing release should be:

```
[ normal dev branches ] -> [develop] -----------.
                               V                V
                               V                V
[hardfork dev branches] -> [hardfork]      [pre-release] -> [testnet-release] -> [testnet]
                                                V
                                                V
                                            [release]
                                                V
                                                V
                                             [master]
```

Git flow for emergency fixes

```
[ normal dev branches ] -> [develop] <-.
                               V       |
                               V       |
[hardfork dev branches] -> [hardfork]  |     [pre-release] -> [testnet-release] -> [testnet]
                                       |
                                       |
                      [hotfix dev branches] -> [release]
                                                   V
                                                   V
                                                [master]
```

**Comment by pmconrad** [comment]
IMO the emergency fix problem is a non-issue because you can always create a new "hotfix" branch from the point where the original "release" branch was merged into main. Also, the proposed solution doesn't really solve the perceived problem, it only reduces the time window where it can occur.

Splitting pre-release into a testnet branch and a mainnet branch introduces an additional risk for missing changes that were applied only on one branch when they were needed on both.

It is true that we have some testnet-only changes, and some changes that must not make it into testnet, for example the hardfork times. The solution for this is to make these changes only on the testnet branch and never merge them back. Merge conflicts are unavoidable in these situations, IMO, and will continue to require manual handling. A better solution for this would be preferrable of course, but I think this is not it.

**Comment by cedar-book** [comment]
Added a flow image. This is based on Bitshares's current GitFlow information (https://github.com/bitshares/how.bitshares.works/blob/master/developers/installation/bitshares_core_gitflow.md)

**Comment by cedar-book** [comment]
A current link is [this](https://github.com/bitshares/dev.bitshares.works/blob/master/source/installation/bitshares_core_gitflow.md) .  I'll add a Bugfix flow.

**Comment by cedar-book** [comment]
I added an Emergency Fix workflow [here](https://github.com/bitshares/dev.bitshares.works/blob/master/source/installation/bitshares_core_gitflow.md#emergency-fix-workflows).
