### ISSUE TITLE
Don't print private keys in log on witness startup

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#93]
_From @theoreticalbts on September 18, 2015 20:41_

_Copied from original issue: cryptonomex/graphene#327_

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/236

**Comment by oxarbitrage** [comment]
before:

`root@NC-PH-1346-07:~/bitshares/issue231/elmato/bitshares-2# programs/witness_node/witness_node --data-dir data/my-blockprod4 --rpc-endpoint "0.0.0.0:8090"  --enable
2604314ms th_a       witness.cpp:89                plugin_initialize    ] witness plugin:  plugin_initialize() begin
2604314ms th_a       witness.cpp:99                plugin_initialize    ] key_id_to_wif_pair: ["BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"]
`

after commit:

`root@NC-PH-1346-07:~/bitshares/issue93/bitshares-core# programs/witness_node/witness_node --data-dir data/my-blockprod4 --rpc-endpoint "0.0.0.0:8090"  --enable
2913554ms th_a       main.cpp:126                  main                 ] Writing new config file at /root/bitshares/issue93/bitshares-core/data/my-blockprod4/confi
g.ini
2913576ms th_a       witness.cpp:89                plugin_initialize    ] witness plugin:  plugin_initialize() begin
2913576ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
2913595ms th_a       application.cpp:431           startup              ] Replaying blockchain due to version upgrade
2913595ms th_a       application.cpp:328           operator()           ] Initializing database...
`

**Comment by kenCode-de** [comment]
Closed as per Alfredo's work in PR #236
